### ISSUE TITLE
reportEvent on FencedFrame is sent as a HTTP Options method.

### ISSUE THREAD

**Issue by k-o-ta** [GoogleChromeLabs/privacy-sandbox-dev-support#104]
Hi.
[Fledge Explainer](https://github.com/WICG/turtledove/blob/main/Fenced_Frames_Ads_Reporting.md#reportevent) explains that `reportEvent` API send HTTP Post request.
However, it appears that `reportEvent` API send HTTP Options request.
Is this an intended behavior?

I am using Google Chrome Canary(114.0.5722.0（Official Build）canary （x86_64)) on MacOS 12.6.

**Comment by kevinkiklee** [comment]
@k-o-ta Apologies for the late reply.  This ticket got buried for a little bit.  

Fenced frames no longer uses CORS, and you should no longer see an OPTIONS method when you run your code with the latest release of Chrome.  Closing this ticket for now, but if you still see the same behavior, please reopen this ticket.
