### ISSUE TITLE
Topics API 検証時に値が取得できない

### ISSUE THREAD

**Issue by nahoito** [GoogleChromeLabs/privacy-sandbox-dev-support#109]
Topics API をOTで検証中ですが、Topics を取得できない頻度が多いように感じます。
最大 3 つのトピックスが取得できるはずという理解ですが、取得できないのは何が原因でしょうか？

**Comment by samdutton** [comment]
**English translation provided by Google Translate**

Topics Unable to get value when validating API #109

I am currently verifying the Topics API with OT, but I feel that there are many cases where Topics cannot be obtained. I understand that I should be able to get up to 3 topics, but what is the reason I can't get them?

**Comment by samdutton** [comment]
This was a test of the new process for non-EN submissions. Closing as resolved!
