### ISSUE TITLE
Picking label sizes for Chrome-facilitated testing

### ISSUE THREAD

**Issue by rowan-m** [GoogleChromeLabs/privacy-sandbox-dev-support#113]
Chrome’s testing modes will provide labeled traffic that can be used by ad techs to construct different experiment arms. We want to provide flexibility to ad techs to run multiple experimental conditions or to test at different levels of traffic. What size of labels would be most useful to you in each mode? 1%, .5%, .25%, or something else?

See https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/ for context.

**Comment by jdwieland8282** [comment]
Before we get into the size of labels, can you give us an example of how the traffic will be labeled?  Where in the oRTB spec will you note the relevant details of the experiment?

**Comment by dmdabbs** [comment]
>What size of labels would be most useful to you in each mode?

A single digit grain should be fine. 

For consistency Mode A and Mode B should use the same scheme.

It is important that Chrome label each Mode B tranche for some time prior to Chrome's cookie suppression so that all can measure before and after. 

This cuts across Sandbox features. Will you at some point have a call(s) to discuss and align, or were you thinkling of covering this in say the biweekly PAAPI (nee FLEDGE) calls?

**Comment by rowan-m** [comment]
> …can you give us an example of how the traffic will be labeled?

@jdwieland8282 for the first part of your question: via #114 we're considering [Client Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Client_hints) as the mechanism, meaning a specific request header that specifies the mode / experiment for that browser. However, we'd like to get feedback on that issue if that would meet your needs, or if not where you'd expect it to appear.

**Comment by rowan-m** [comment]
> This cuts across Sandbox features. Will you at some point have a call(s) to discuss and align, or were you thinkling of covering this in say the biweekly PAAPI (nee FLEDGE) calls?

@dmdabbs good request! I think we should certainly plan some explicit office hours sessions and I'll share the comment with the various people running individual calls for their view on where it makes sense to integrate.

**Comment by piwanczak** [comment]
Wrt Mode A it would be good to start with something small like 0.1%, and start quick

**Comment by clementsimon** [comment]
Closing - please refer to the [Chrome-facilitated testing article](https://developers.google.com/privacy-sandbox/setup/web/chrome-facilitated-testing) for the size of label groups.
