### ISSUE TITLE
Will there be an opt-out for mode-B third-party cookie deprecation testing starting in Q1 2024? 

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#119]
I see there will be [no user opt-in](https://developer.chrome.com/blog/shipping-privacy-sandbox/#mode-b:~:text=There%20is%20no%20opt%2Din%20for%20this%20mode%2C%20as%20it%20will%20be%20applied%20globally.) when Chrome deprecates third-party cookies for up to 1% of browsers in Q1 2024. Since this is a testing period, will there be a way for users to opt out of third-party deprecation if a site is having issues? It's not clear from the documentation.

**Comment by andreipop** [comment]
Also keen to know if there is an option to opt out from mode-B for the same reasons as mentioned above.

**Comment by clementsimon** [comment]
Hi there and sorry for the delay in responding. While a user cannot opt-out from membership of the mode B group, they can temporarily enable third-party cookies on a site-by-site basis by using the dedicated button (the eye icon) in the omnibox.
