### ISSUE TITLE
Sites that can always use cookies functionality

### ISSUE THREAD

**Issue by dcohenEG** [GoogleChromeLabs/privacy-sandbox-dev-support#120]
After phasing out third party cookies, will Chrome continue to support the "Sites that can always use cookies" functionality in the Privacy and Security settings (see screenshot)? Specifically, will the functionality continue to exist for entries that are managed by the enterprise chrome settings (the first five in the screenshot) and for those entries that are managed by the user (the last entry that says "Including third-party cookies on this site")?

I didn't find any references to this functionality specifically in any of the documentation.

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/29263489/232e65d2-9614-403f-9482-9d367a30a2bb)

**Comment by dcohenEG** [comment]
I enabled the flag specified [here](https://developer.chrome.com/blog/shipping-privacy-sandbox/#user-controls), the `chrome://flags/#privacy-sandbox-settings-4` flag,  and see the following section under Privacy and security > Third-party cookies.

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/29263489/69c00079-eef4-42db-8ec8-2867d48e1bcb)

The wording is different, but it sounds like the same functionality. Does this mean that the functionality is being kept alongside the Privacy Sandbox initiative?

**Comment by rowan-m** [comment]
We have a recent blog post which covers the start of the updates to enterprise policies around opt-out: https://developer.chrome.com/blog/cookie-countdown-2023oct/#enterprise-support
