### ISSUE TITLE
How will First Party Sets treat unpartitioned cookies after 3rd party cookie deprecation?

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#123]
The [CHIPS page ](https://developer.chrome.com/en/docs/privacy-sandbox/chips/#:~:text=Cookies%20must%20be%20set%20with%20a%20new%20attribute%20in%20order%20to%20be%20sent%20on%20cross%2Dparty%20requests%20once%20(unpartitioned)%20third%2Dparty%20cookies%20are%20obsoleted.)states that cookies must be set with the Partitioned attribute in order to be sent on cross-party requests once (unpartitioned) third-party cookies are obsoleted.

How does this affect First Party Sets? Assume site test1.com and test2.com are in the same FPS. Test2.com sets an unpartitioned cookie. Will Test1.com still be able to access test2.com's cookie?

**Comment by krgovind** [comment]
> How does this affect First Party Sets? Assume site test1.com and test2.com are in the same FPS. Test2.com sets an unpartitioned cookie. Will Test1.com still be able to access test2.com's cookie?

Note that test1.com cannot directly access test2.com's cookie (if it did, this would be a violation of the [Same Origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) for cookies), even in today's status quo where cross-site cookies exist. However, test2.com can access it's _own_ cookies. 

After cross-site cookies are disabled; if test1.com and test2.com are in the same FPS, test2.com can continue to access it's own cookies only after Storage Access API (SAA) is appropriately invoked. See [this article](https://developer.chrome.com/docs/privacy-sandbox/first-party-sets-integration/) for details.

Usually, this means that test1.com can make a credentialed request to test2.com, and the browser will attach test2.com's cookies as long as the storage access permission has been granted to the site (by virtue of the FPS+SAA integration).

**Comment by bretticus-mc** [comment]
Yeah I failed to include, Test2.com is embedded on Test1.com. In another tab, Test2.com is its own top-level site. Test2.com sets an unpartitioned non-CHIPS cookie after 3rd-party cookie deprecation. So in this case, will the embedded test2.com be able to access the unpartitioned cookie set by test2.com in the next tab?

**Comment by krgovind** [comment]
> So in this case, will the embedded test2.com be able to access the unpartitioned cookie set by test2.com in the next tab?

Yes! As long as Storage Access API is invoked correctly before the relevant requests to test2.com are made, it will be able to access the unpartitioned cookie.
