### ISSUE TITLE
Help understanding the behavior of unpartitioned cookies after third-party deprecation

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#126]
Hello,

After Chrome deprecates third-party cookies, how will unpartitioned cookies be treated? Will they be automatically partitioned by top-level site like CHIPS? Will unpartitioned Same-Site=None cookies simply be disabled? I'm curious about two scenarios:

1. Will an embedded third-party iFrame SharedWorker's fetch with credentials:include still contain the unpartitioned Same-Site=None cookie?

2. If I have Site B embedded in an iFrame on Site A. Site B sets an unpartitioned Same-Site=None cookie. If I duplicate the tab, will the 2nd tab's embedded Site B still have access to the unpartitioned cookie set by Site B in the first tab?

**Comment by dmdabbs** [comment]
>After Chrome deprecates third-party cookies, how will unpartitioned cookies be treated? Will they be automatically partitioned by top-level site like CHIPS?

CHIPS is not automatic. The developer [opts in](https://github.com/privacycg/CHIPS) using a new `Partitioned` attribute.

**Comment by bretticus-mc** [comment]
Ok then what's the expected behavior of unpartitioned Same-Site=None cookies after Chrome deprecates third-party cookies? Specifically:
1. Will a SharedWorker's fetch with credentials:include still contain the unpartitioned cookie
2. The embedded duplicate tab scenario I listed above?

**Comment by dmdabbs** [comment]
>Will unpartitioned Same-Site=None cookies simply be disabled?

That's my expectation given Chrome's intent to deprecate cross-site unpartitioned cookies.

**Comment by amedina** [comment]
As pointed out by @dmdabbs and the referenced [docs](https://github.com/privacycg/CHIPS#chips-opt-in-partitioned-cookies), third parties may opt-in to using CHIPS by setting the Partitioned attribute. Third party cookies that do not have that attribute will not be accessible.

**Comment by amedina** [comment]
Closing this issue but feel free to follow up any with further questions!
