### ISSUE TITLE
Questions FedCM API demo does not work with "Block third-party cookies" enabled

### ISSUE THREAD

**Issue by solatsuta** [GoogleChromeLabs/privacy-sandbox-dev-support#141]
## Overview
Hello, I am developing an IdP that is affected by third-party cookie blocking.
From an RP's iframe, I call a URL that executes the FedCM API of the IdP and expect the RP to be able to log in.
In fact, I have incorporated the FedCM API and confirmed that the use case is satisfied.

However, if you enable "Block third-party cookies" in the Chrome settings, the FedCM API will not work.
I would like to confirm that this is the intended behavior as it is the same in the official demo, etc.
- https://fedcm-rp-demo.glitch.me/
- https://fedcm-top-frame.glitch.me/

Thanks for reading this far.
This issue is made in translation. Sorry if the language is strange.

### How to reproduce
1. enable "Block third-party cookies" in chrome://settings/cookies 
   - Normal operation can be confirmed by disabling it.
2. visit the following page
   - https://fedcm-rp-demo.glitch.me/
   - https://fedcm-top-frame.glitch.me/
3. console.log confirms that the token cannot be retrieved
   - look at console.log('Error retrieving a token.')

## Question  
- With Chrome's "Block Third-party cookies" enabled, does the third-party FedCMAPI called from within an RP iframe work?
  - If so: Is it correct to say that it is a bug if it doesn't work now?
  - If not: How should use cases where the RP exchanges session state with the IdP via an iframe be avoided under "Block Third-party Cookies"?
How should this be avoided under "Block Third-party cookies"?

## Supplemental
- Chrome version is 115.x
- Iframe on RP with identity-credentials-get attribute
  - e.g. `<iframe src="3rd-party.example" allow="identity-credentials-get"></iframe>`.
  - Reference: https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API#permissions_policy_integration_and_iframe_support

**Comment by samuelgoto** [comment]
> will be enabled in the future when Chrome starts to phase-out default support for third-party cookies.

Yes, that's correct. So far, the belief is that if we can ship the [IdP Sign-in Status API](https://groups.google.com/a/chromium.org/g/blink-dev/c/y-eie2d-1iU/m/7uH31AQNDAAJ) we will be able to enable FedCM **without** 3PC. So, if all goes according to plan, yes, we would have FedCM enabled **without** 3PC at some point.

**Comment by samuelgoto** [comment]
> Hello, I am developing an IdP that is affected by third-party cookie blocking.

Any chance you have a link handy that we could use to try your IdP ourselves? Any chance that's something that is publicly available? 

> From an RP's iframe, I call a URL that executes the FedCM API of the IdP and expect the RP to be able to log in.
> In fact, I have incorporated the FedCM API and confirmed that the use case is satisfied.

I'm glad to hear that your use case is satisfied and that the FedCM can be of help through the process!!

> Thanks. This issue has been resolved.
> Looking forward to further progress on 3PC.

Note that, for FedCM to operate without third party cookies, it is conditioned on the use of the IdP Sign-in Status API. So, in case you haven't already, please give the [Origin Trial](https://developer.chrome.com/blog/fedcm-chrome-116-updates/#idp-signin-status) a try, and please do let us know if you run into any trouble!

**Comment by samuelgoto** [comment]
> The IdP domain for the service is https://connect.mobage.jp/.

Is this a FedCM-compatible IdP? We can't seem to find the .well-known file in it:

```
curl -L https://mobage.jp/.well-known/web-identity
```

**Comment by samuelgoto** [comment]
> we have tested in our development environment that FedCM will satisfy our use case. 

Ah, glad to hear that it satisfies your use case!

Can you give me a sense of which RPs would be using the https://mobage.jp/? If just a few, have you considered [First Party Sets](https://developer.chrome.com/docs/privacy-sandbox/first-party-sets-integration/) instead?
