### ISSUE TITLE
Atribution reporting API with DSPs for measurement purposes

### ISSUE THREAD

**Issue by Vas-we** [GoogleChromeLabs/privacy-sandbox-dev-support#142]
Dear Colleagues,
We need to figure out how to set up atribution reporting API with DSPs for measurement purposes. 

Based on the instructions provided by Google we guess that the necessary steps are the following:

1) On the publisher web-site (where ad should be displayed)  a dedicated <iframe> tag in the allow=”attribution-reporting” ad block should be added, so the Google will know that Attribution API is allowed. 

2) it's needed to add  'attributionsrc' attribute to <a>, <img> with 3P ad trackers pixels
But the issue is that DSPs do not always control the top iframe on the site (publisher wrappers, video platform wrappers, header-bidding, etc.) so they can't implement an iframe. 
And another question is that if the image is not placed through the img tag (but with canvases, for example) or no picture at all, how it should be implemented? 

Can someone provide some hints how the process in this case should be organized?

**Comment by captify-mgruau** [comment]
Regarding your first point, as per this announcement, it seems that for now this might not be needed: https://groups.google.com/a/chromium.org/g/attribution-reporting-api-dev/c/MV8gQ4sTc8w/

By default attribution-reporting is allowed. 

On your point 2., from what I understand attributionsrc can be set within the <a> tag of the creative, so again no need for an iframe: https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting/register-attribution-source/

**Comment by clementsimon** [comment]
Thanks @Vas-we for the questions, what @captify-mgruau said is correct.
