### ISSUE TITLE
Question Want to using cookies on subdomains.

### ISSUE THREAD

**Issue by solatsuta** [GoogleChromeLabs/privacy-sandbox-dev-support#144]
## Overview
Hi, I have a use case in a 3rd party context that I don't know how to solve.
I would very much like to know.

Specify the `DOMAIN attribute` when issuing the cookie.
I want to send this cookie in a request within an iframe.
Currently, if privacy sandbox is enabled and 3rd party cookies are blocked, it cannot be sent.
I understand that this is a use case where the 3rd party cookie initiative is blocked because the 1st party domain and the domain where the cookie is used are different.

_Thanks for reading this far.
This issue is made in translation. Sorry if the language is strange._

### Cookie-issuing domain
As an example, this domain behaves as an IdP.
- Host: 3rd-party.example
- Cookie Domain Attributes: .3rd-party.example
- The cookie to be set here will be called `Cookie Foo`.

### Subdomain that uses cookie
This DOMAIN, for example, may assume a variety of built-in interfaces.
Chat, for example.
Since it is a subdomain that I manage, I verify that it is authorized by referring to the `Cookie Foo` set by the IdP.
- Host: 
  - chat.3rd-party.example
  - bar.3rd-party.example
  - baz.3rd-party.example
  - etc.

### request User Agent
Load 3rd-party.example and chat.3rd-party.example in an iframe.
This DOMAIN is not a DOMAIN that I manage, but rather an unspecified domain for all RPs that use my IdP.
- Host: 1st-party.example

## Use case
1. Request 1st-party.example.
2. 1st-party.example loads 3rd-party.example in an iframe.
3. 3rd-party.example uses FedCM for authentication.
4. 3rd-party.example sets a `Cookie Foo` with information related to authentication.
  4.a.  I use CHIPS at this time.  
5. If 1st-party.example was successfully sign-in, load chat.3rd-party.example in an iframe.
6. chat.3rd-party.example receives `Cookie Foo`
7. Once the integrity of the `Cookie Foo` is verified, the chat window is responded to.

## Question
Is there a way to achieve the use case?
We are using CHIPS to send cookies from 1st-party.example to 3rd-party.example.
If this use case can be met, CHIPS is not a requirement.

**Comment by johannhof** [comment]
Hi @solatsuta, I think your use case should work given that you can set the Domain attribute as of https://github.com/privacycg/CHIPS/issues/43. Are you running into any issues with your outlined setup? :)

**Comment by johannhof** [comment]
`__Host-` should not be required to set a `Partitioned` cookie, see https://github.com/privacycg/CHIPS/issues/30. I'm curious if you've read about that somewhere? So you should be free to remove the prefix and use the domain attribute.

**Comment by johannhof** [comment]
No worries at all, glad this was an easy fix :)
