### ISSUE TITLE
Source_event_id

### ISSUE THREAD

**Issue by Natalia-user** [GoogleChromeLabs/privacy-sandbox-dev-support#145]
Hi all,
1) do you know if the 64-bit limitation for the event_source_id  will be kept when 3P cookies will be totally deprecated?
Or it can be changed when the debug time will be over?
2) Also it's said in the documentation that the value of this parameter can vary, what does variability depend on?who control that?
3) Will we always receive in the reports in these 64 bits exactly what we put there while source registration? or the browser can somehow change these 64bits and we will get something different from what we put there during registration.
For example, the browser can leave only 32 bits and set the rest to zero and in the report we will get only 32 bits

Thanks!

**Comment by clementsimon** [comment]
Hi @Natalia-user - thanks for your questions and sorry for the delay in responding.

1. Currently there are no plans to change the 64 bit limitation on event-level report `source_event_id`
2. `source_event_id` is a field that can be set by the ad-tech during source registration
3. The browser does not alter what is put in the `source_event_id` field

Thanks

**Comment by clementsimon** [comment]
Closing this issue as answered but please re-open if you have any more questions.
