### ISSUE TITLE
Question The intended Header:Origin is not sent to the Assertion Endpoint in FedCM.

### ISSUE THREAD

**Issue by solatsuta** [GoogleChromeLabs/privacy-sandbox-dev-support#152]
## Overview
Hi, I am implementing FedCM in a 3rd party context.

I have tried a flow that executes the `FedCM API` from a [Cross-Origin iframe](https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#call-fedcm-from-within-a-cross-origin-iframe), but the Origin Header requested in the [Assertion Endpoint ](https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#id-assertion-endpoint)is the origin of the iframe.
I am not expecting the origin of the iframe, but the origin of the topFrame that is loading the iframe.

_Thanks for reading this far.
This issue is made in translation. Sorry if the language is strange._

## Details
- RP: `rp.example`
- IdP: `idp.sample`

### process
1. `rp.example` loads `idp.sample` in an iframe.
2. The `idp.sample` loaded in an iframe executes the FedCM API.
3. Assertion in the FedCM Process sends an Origin Header to `idp.sample`.
4. The Assertion Endpoint receives `idp.sample` in the Origin Header.

### What we tried
- Set `identity-credentials-get` in allow attribute of iframe
- The RP sets the `Permissions-Policy` in the response header.
  - e.g. `Permissions-Policy: identity-credentials-get=(self "https://idp.sample")`

## Question
I want to receive the Origin of the `rp.example`. 
can't I receive the Origin of the RP with the FedCM API running on the `idp.sample` loaded in the Cross-Origin iframe?

Please let me know if I'm setting something up wrong or missing a reference.

**Comment by npm1** [comment]
It seems correct to me that the FedCM fetches will use the Origin of the iframe, since that is where the FedCM call is originating. I can see why you want to check the RP origin. Can the embedded IDP iframe do that check?

**Comment by cbiesinger** [comment]
I'm not sure I understand the concern. The origin can not be spoofed; it matches the iframe. The toplevel frame can not initiate a FedCM call in the iframe unless the iframe specifically cooperates to allow it.

Could you share a bit more details on your setup?

**Comment by cbiesinger** [comment]
> @cbiesinger
> 
> > The origin can not be spoofed; it matches the iframe.
> 
> The prevention of Origin spoofing is ensured by the fact that the Origin in the Request Header and the Origin associated with the client_id registered in the IdP are identical.

Yes -- so in your use case, the client_id's registered origin is the toplevel URL and not the iframe's URL?

Is the iframe loaded from the IDP's origin? If not, what is the relationship between the iframe and the toplevel? Why does the iframe have to make the FedCM call even though the client ID is not registered to it?

**Comment by npm1** [comment]
My suggestion is to ask the top frame to use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to declare its origin to the iframe (it's probable you already need some postMessage to pass some other information from the top frame to the iframe anyways). The iframe can verify it is telling the truth by checking it matches `event.origin`. It is correct that the top frame origin is not available from the FedCM fetches themselves.

**Comment by npm1** [comment]
Origin is right. I've let them know (it's possible the translation was not updated after changes to the original doc).

**Comment by npm1** [comment]
Thanks for the feedback, I've asked if we can add some clarification on iframe embedder origin validation. I think your understanding is correct but I do not have closing powers here :)

**Comment by JackJey** [comment]
Hi @solatsuta 
Thanks for reaching me out. Yes we know the JP translated contents has large diff with original En version. sorry for confusing you.
Now we are working on updating En version for merging some updates recently happened. And then re-translating it into JP again.
Thanks.
