### ISSUE TITLE
Add labels for browsers not in Mode A nor B

### ISSUE THREAD

**Issue by lbdvt** [GoogleChromeLabs/privacy-sandbox-dev-support#153]
Some SSPs won't be participating in Chrome-facilitated testing, and those SSPs may not extract and/or forward in the bid stream the labels related to mode A and B.

A DSP receiving a bid request without label will then not know whether that browser is outside of mode A and B, or whether the label has been lost at some point in the bid stream (which can be very complex, with cascading SSPs).

Adding labels to browsers outside of Mode A and B would _partially_ solve this. 

If that "reference pop" label is received, that's a strong indication of the browser population, and that the label has been sent all along the bid stream.

**Comment by thegreatfatzby** [comment]
Was this agreed to, or should we discuss at one of the wednesday meetings?

**Comment by dmdabbs** [comment]
>Was this agreed to, or should we discuss at one of the wednesday meetings?

When the notion of labeling debuted we raised it in the Wednesday FLEDGE forum and it was determined to be beyond that team's remit. We can certainly raise again. Perhaps @rowan-m has a suggestion.

**Comment by ning-hu** [comment]
My concern around this is that if a user clears their cookies and no chrome label is sent, then we can't tell if we didn't request it versus the user has no label.

**Comment by samdutton** [comment]
After discussion between teams working on the Chrome-facilitated testing program, we have decided not to label Chrome browsers that are not in the Mode A or Mode B groups.

This decision has been based on several factors. Firstly, there is a risk of ecosystem burn-in with the JavaScript API. (By burn-in we mean that sites come to depend on the existence of the API, making the API difficult to remove in future.)

It might be possible to mitigate privacy concerns with a "neither A nor B" label, but this would add to engineering complexity, make it more difficult ensure that labeling is performant, and lead to delays in the timeline.

**Comment by samdutton** [comment]
Closing this, as no comments in three weeks, but feel free to reopen.
