### ISSUE TITLE
Will assignation to mode A and mode B be at browser or user level?

### ISSUE THREAD

**Issue by lbdvt** [GoogleChromeLabs/privacy-sandbox-dev-support#155]
For a user using several Chrome instances, e.g. on different devices, and logged-in on these different instances using the same Google account, will all those instances be consistently in the same mode A or mode B population?

Or is the mode A / mode B assignation at browser level, so those instances may end up in different populations?

**Comment by dmdabbs** [comment]
Yes, clarifying the terms of the test regime is welcome. 

The initial description in the testing modes doc describes Mode B as (emphasis mine)

>Mode B: Chrome globally disables third-party cookies for some portion of all Chrome _**users**._

Which I read as users of Chrome, not _indivduals_ because later (where it seems more specific) Mode B is described in terms of instances of Chrome

>Chrome will deprecate third-party cookies for up to 1% of browsers.

The preference would be for maintaining this labeling on an _individual user_ basis, across all his/her Chrome instances.

**Comment by thegreatfatzby** [comment]
Slightly separate from multiple instances but still related to browser vs user, will any user action result in the label assignment being modified/deleted? Will that label persist between Incognito mode and non-Incognito? Would wiping out cookies change the label, or just temporarily wipe the cookie but then a subsequent 'set-cookie' response header would result in the same label for sure becoming the cookie again?

**Comment by dmdabbs** [comment]
Noting here that in today's weekly WICG PA API call, Michael Kleber [addressed](https://docs.google.com/document/d/1Kr0hpfQ_Q1LX1aN00D5k_09yV_a7WE9RSn69nS3nZho/edit) this...

>[David D] You mentioned “percentage of users” in the devrel document, but I believe you mean “instances of chrome browsers”... I think you should disambiguate that because it gives the impression that this is referring to actual people behind the keyboard.
[MK] You are 100% correct.
[Kevin] I'll pass that comment along and update this doc

**Comment by clementsimon** [comment]
This has been clarified in the [Chrome-facilitated testing article](https://developers.google.com/privacy-sandbox/setup/web/chrome-facilitated-testing):

> Chrome browser in this context refers to a Chrome client: a Chrome installation on a device. Each individual user [data directory](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md) constitutes a distinct client.
