### ISSUE TITLE
Questions regarding third-party storage partitioning feature

### ISSUE THREAD

**Issue by DylaDCO** [GoogleChromeLabs/privacy-sandbox-dev-support#165]
Dear experts, 

We are working on a web application inserted across different web app services using **iframes**.

The new _[local storage partitioning](https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning)_ feature is a breaking change for our current architecture as our webapp instances were communicating through a shared state from different iframe in different parent domain.

We're urgently trying to implement our new solution (using web sockets), but we are concerned it would come by surprise and starts an outage so we'd like to know more about release plans.

As a temporary solution, we are disabling the experiment flag `Experimental third-party storage partitioning` for our users (Chrome profile managed by our company).

![Screenshot 2023-10-10 at 16 50 09](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/140980119/15888a89-88fc-4558-90ac-d1b54fc15f13)

Questions:
- Is there currently any better solution to disable the _third-party storage partitioning_?

- Knowing the [proposal document](https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/#implementation-status) mentions a "_fully available in Chrome Stable mid-year 2023_" release, do you know what is the current deployment status? When will we lose the ability to disable this experiment?

- After the release of this feature (out of the experiment phase), will it also introduce a feature switch (like the third-party cookie option?
![Screenshot 2023-10-10 at 11 39 48](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/140980119/8e1d4c2f-746b-4bfd-8101-629bd1712e9d)

Thanks!

Best regards,
Dylan

**Comment by miketaylr** [comment]
Hi @DylaDCO, thanks for the issue!

> As a temporary solution, we are disabling the experiment flag `Experimental third-party storage partitioning` for our users (Chrome profile managed by our company).

We also have https://chromeenterprise.google/policies/#DefaultThirdPartyStoragePartitioningSetting (maybe you're using that!).

> * Is there currently any better solution to disable the _third-party storage partitioning_?
> *

See above, for managed environments. We also have a [deprecation trial available](https://developer.chrome.com/blog/storage-partitioning-deprecation-trial/), but that's going to be more temporary than the policy above.

> * Knowing the [proposal document](https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/#implementation-status) mentions a "_fully available in Chrome Stable mid-year 2023_" release, do you know what is the current deployment status? 

We have deployed this feature to 100% of stable users on 115 and above. 

> When will we lose the ability to disable this experiment?

There isn't an expiration date for the enterprise policy today, but I wouldn't count on it lasting _forever_. But we have no plans to remove it in the next year, and will give plenty of notice once we do have an expiration date in mind.

The deprecation trial will be valid until just before the Chrome 127 release.

> After the release of this feature (out of the experiment phase), will it also introduce a feature switch (like the third-party cookie option?

We don't have any current plans to expose 3P partitioned storage in settings. Feel free to file a feature request via crbug.com/new though!

**Comment by DylaDCO** [comment]
Thanks Mike for your detailed answer.

One last thing, we also discovered the [ThirdPartyStoragePartitioningBlockedForOrigins](https://chromeenterprise.google/policies/#ThirdPartyStoragePartitioningBlockedForOrigins) setting and we'll use it for now.

Just to confirm, theoretically if our app `www.app.com` is injected in several services `www.service-a.com`, `www.service-b.com`, `www.service-c.com`. We must set these 3 domains in the `ThirdPartyStoragePartitioningBlockedForOrigins` setting? Or only the inserted app domain `www.app.com`?

Could you confirm that the blocked origins are the parent iframe domains?

**Comment by miketaylr** [comment]
That's a great question. Let me tag @arichiv who will know with more confidence. :)

**Comment by arichiv** [comment]
The list of urls in ThirdPartyStoragePartitioningBlockedForOrigins is checked against the top-level site only.

"Allows you to set a list of url patterns that specify top-level (the url in the tab's address bar) origins which block third-party storage partitioning (partitioning of cross-origin iframe storage)."

All three domains would need to be added.

**Comment by arichiv** [comment]
The deprecation trial does have a mode for matching against a third-party frame URL instead of just the top-frame URL. https://developer.chrome.com/blog/storage-partitioning-deprecation-trial/

**Comment by DylaDCO** [comment]
Thanks for the added details on the `ThirdPartyStoragePartitioningBlockedForOrigins` setting. 

We're still having issues to propagate the setting to all our users. So, I am investigating the usage of the deprecation trial.


Our goal is to make our app **`www.my-app.com` share the same local storage** **whenever** the app is **in a iframe** under `www.service-a.com`, or `www.service-b.com` or **simply browsed directly without iframe**.

So I created a deprecation trial token targeting `www.my-app.com` and checked the 3rd party toggle.

![Screenshot 2023-10-12 at 16 09 17](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/140980119/2e37af08-b4cd-4130-8bee-f1a57582d141)

The chrome inspector is telling me the origin is wrong, although the value is identical. Is the 3rd party origin also supposed to mentioned somehow?

When trying a token without the 3rd party toggle, the token is recognised (and the trial enabled) but the local storages are partitioned, which is not helping our case.

I am new to the deprecation trial mechanism, Is there anything I am missing?

**Comment by arichiv** [comment]
The policy only impacts enterprise users, the deprecation trial can impact all users.

The typical flow for the deprecation trial for third-party origins is to have whatever site wants to embed the iframe embed a script from that third-party origin. The script would inject the token and then embed the iframe itself.

**Comment by DylaDCO** [comment]
We'll focus on deploying the policy setting then. Thanks everyone for all the valuable input 😃
