### ISSUE TITLE
Clarifications about third-party deprecation trial

### ISSUE THREAD

**Issue by vs-amzn** [GoogleChromeLabs/privacy-sandbox-dev-support#168]
I saw that yesterday there was an update here: https://developer.chrome.com/blog/cookie-countdown-2023oct/#request-additional-time-with-the-third-party-deprecation-trial-for-non-advertising-use-cases

A few questions:
1. Is this deprecation trial one that would require a third-party service to opt in to? For example, if an application (domain A) relies on the use of third party cookies when in an embedded context, would this trial allow the owners of that application to enter the deprecation trial? In this example, anything that embeds the third-party application (after registering the third-party that is embedded) would continue to work as is for all Chrome users that interact with that third-party embed, is that correct? My understanding is that this is an allowlist that owners of applications that are (1) embedded in a third-party context and (2) rely on the use of third-party cookies, would have to register for.
2. What is the timeline for this trial period? Is there a rough estimate for how long this trial will last?
3. If there is no timeline, when will this timeline be released?
4. What is the scope of the review process? 

Thank you.

**Comment by johannhof** [comment]
Hi @vs-amzn, I want to note that we've seen your questions and will follow up here in the next few weeks, as some of the details on the DT are still being finalized and we'd like to publish them in a coordinated fashion.

**Comment by vs-amzn** [comment]
Thank you for the update! 

Is there a way for this information to be published sooner? As applications are getting ready for the 1% rollout starting Q1 2024, understanding the details here ASAP would be extremely helpful in coordinating efforts for all parties.

**Comment by johannhof** [comment]
I understand, we're working to get this published as soon as possible. :)

**Comment by samdutton** [comment]
@johannhof @vs-amzn Closing this as answered (as per Johan's comment) but feel free to reopen.

**Comment by vs-amzn** [comment]
@samdutton Not sure why this was closed, I haven't seen any new details published about the timeline of the deprecation trial. The last time this https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/ was updated was 10/11/2023. Do we know when these details will be released? From the documentation, it sounded like it was going to be announced before the end of October.
