### ISSUE TITLE
Source for views not getting registered via fetch call

### ISSUE THREAD

**Issue by kravish1** [GoogleChromeLabs/privacy-sandbox-dev-support#169]
H1,
I was trying to register attribution sources based of your article https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting/register-attribution-source/

This is my code
```
const attributionReporting = {
          eventSourceEligible: true,
          triggerEligible: false,
        };

fetch(attributionUrl, { keepalive: true, attributionReporting });
```

I am able to get the navigation (click) source type registration working but the event (view) source type is not getting registered in chrome://attribution-internals

I do see the endpoint getting invoked and I see the response header with Attribution-Reporting-Register-Source:
{"source_event_id":"9759258831728736887","destination":"https://linkedin.com/","expiry":"2592000","priority":"0","event_report_window":"3600"}

PS the source registration for views works fine if an img tag is used.

**Comment by maybellineboon** [comment]
Hi @kravish1 ,

Would you be able to share your setup or sample page where the code is working? Tried to work this out and I can see event (view) level source getting registered on my end. Would be happy to see what might be going on.

My code uses both a script tag for the dsp js where the js calls the register-source url. And also a script where the publisher calls the register-source url. Both used fetch and window.fetch.

**Comment by kravish1** [comment]
@maybellineboon, I was able to get window.open working. Is there an api to pass attributionsrc for links that transition in-app (does not navigate to a new tab).

**Comment by maybellineboon** [comment]
Hi @kravish1 ,

You can use the "_self" option for window.open if you want to open it in the current tab or use the target in window.open(url, target) to place your iframe's name in.

https://developer.mozilla.org/en-US/docs/Web/API/Window/open

**Comment by kravish1** [comment]
@maybellineboon , for my specific case, we don't use window.open for opening the page in-app, instead we use the ember framework's router.transitionTo. I've 2 questions
1) Is window.open the only javascript api for us to pass the attributionsrc? 
2) can we use fetch call or XMLHttpRequest to pass the attributionsrc for **click** through conversion?

**Comment by maybellineboon** [comment]
Hi @kravish1 ,

From our [explainers](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#registering-attribution-sources), Javascript will have the fetch and open method. Would like to understand if fetch addresses this issue? fetch should be able to call your attributionsrc and register a source without opening a new window.

**Comment by kravish1** [comment]
@maybellineboon , `fetch` addressed the **view** through conversion by calling it in the below manner.
```
const attributionReporting = {
          eventSourceEligible: true,
          triggerEligible: false,
        };

fetch(attributionUrl, { keepalive: true, attributionReporting });
```

However, I wanna know if `fetch` can be used for **click** through conversion by setting  `eventSourceEligible` to `false`?

**Comment by maybellineboon** [comment]
Hi @kravish1 ,

Looked into this further. Here's a few findings:
1) For the initial question on why fetch is registering `clicks` and not `event`, we can confirm that fetch performs only `event`.
2) Window.open will register `click` or `navigation`.
3) fetch and XMLHttpRequest (this is available) will register `event` or `views`.

As for `click` sources, you will need to use window.open or `<a>` tags. And both will need a `click` event and will need to `navigate

**Comment by kravish1** [comment]
@maybellineboon , thanks a lot for your inputs. This is helpful.
