### ISSUE TITLE
Protected Audience API 

### ISSUE THREAD

**Issue by TheTamFamily** [GoogleChromeLabs/privacy-sandbox-dev-support#171]
Morning,

In PAAPI the advertiser can delegate to another buyer.  The buyer can create the interest group and buy on behalf of the advertiser.  When creating the interest group, the buyer specifies the biddingLogicUrl and the renderUrl.  It is my understanding that both these urls must be from the same owner domain. For example, if owner is https://domainA.com then biddlingLogicUrl and renderUrl resources must also be from https://domainA.com.  

Is it possible to have the biddingLogicUrl and renderUrl from a different domain i.e. delegate the bidding and ad serving to another party.  The current programamtic landscape allows for:

1. Customer Data Platforms to create and activate audiences i.e. interest groups.
2. DSP as the buying platform.
3. An Ad Server such as Campaign Manager 360, Sizmek to do the trafficking (ad serving).

All 3 are different tech paltforms owned by different parties.  

Kind regards,

David

**Comment by rdgordon-index** [comment]
https://github.com/WICG/turtledove/issues/813 is a related discussion

**Comment by dmdabbs** [comment]
Hi @TheTamFamily. Only the buyer's script-loading fields have this. 

>All fields that specify URLs for loading scripts or JSON (biddingLogicURL, biddingWasmHelperURL, trustedBiddingSignalsURL, and updateURL) must be same-origin with owner ....

A renderURL can come from anywhere, though in a [buyer security section](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#14-buyer-security-considerations) they counsel to not mix joining and rendering.

**Comment by TheTamFamily** [comment]
Thanks @dmdabbs.  I thought this is the case.
