### ISSUE TITLE
Attribution demo is not working

### ISSUE THREAD

**Issue by raychaudhuri-amitava** [GoogleChromeLabs/privacy-sandbox-dev-support#174]
When I am running the demo using firebase (firebase emulators:start --project none), I am seeing the following 3 issues:
1) No source is registered in chrome://attribution-internals/
[No Source Registration](https://drive.google.com/file/d/1qrQvRlJVSLfKotCVDPZ8Yoqs_z0XZfmT/view?usp=sharing)

2) The status in "Source Registration" tab is  Rejected: prohibited by browser policy
[No source event reporting status](https://drive.google.com/file/d/1qVh1POOvPbV3GSM5TPK_7bMH3gT-xgKK/view?usp=sharing)

3) The Event-Level Status "Failure: Prohibited by browser policy" and Aggregatable Status "Failure: Prohibited by browser policy" in Trigger Registrations
[No trigger event aggregatable and event level status](https://drive.google.com/file/d/1eyQiE1POJZV5afgnpLKZZfQ-s1vQ7G2m/view?usp=sharing)

Due to the above, I am never able to see Event-Level Reports and Aggregatable Reports. 

I need help to understand why the demo is not working in my machine, I tried in Ubuntu and Mac both. Please let me know what should I do to make sure that the demo runs and I can see the aggregation in chrome://attribution-internals
//cc
@maudnals

**Comment by jiali-ebay** [comment]
> This is now working.

**Comment by jiali-ebay** [comment]
Hi @raychaudhuri-amitava , how did you make it work? I encountered the same issue on my Mac.

**Comment by Peter-WF** [comment]
Hi @raychaudhuri-amitava, I encountered a similar problem on my Android phone. 

demo: https://arapi-publisher.web.app/

video: https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/13869200/4b13bacb-3e2e-44db-bfc8-5d388b374d9e

**Comment by raychaudhuri-amitava** [comment]
I am not sure about the android usecases. Update chrome://flags/#privacy-sandbox-enrollment-overrides with https://arapi-adtech.web.app/ to make it work. 

thanks & regards
amitava
