### ISSUE TITLE
Third Party Storage Partitioning

### ISSUE THREAD

**Issue by Floxbu** [GoogleChromeLabs/privacy-sandbox-dev-support#176]
I work for a large company that uses Twilio to enable agents working remotely to process inbound and outbound calls within a secure company-controlled and monitored online environment, on their own computers within Google Chrome. 

We were recently told that Twilio also computes the hours that we work, and in order for it to continue to do so correctly, we had to adjust a crucial setting in Google Chrome, specifically under "Experimental third-party storage partitioning."

The setting was to be changed from "default" to "disabled."

I'm wondering what effect(s) that doing this will have, in general, and in particular with respect to privacy. Please keep in mind when you answer that I'm not an IT professional or expert.

Thank you kindly. Floxbu

**Comment by miketaylr** [comment]
> We were recently told that Twilio also computes the hours that we work, and in order for it to continue to do so correctly, we had to adjust a crucial setting in Google Chrome, specifically under "Experimental third-party storage partitioning."

Fascinating.

A preferred outcome would probably be for your company to engage w/ Twilio to enroll in the deprecation trial: https://developer.chrome.com/blog/storage-partitioning-deprecation-trial/ or look into enterprise policies: https://chromeenterprise.google/policies/#DefaultThirdPartyStoragePartitioningSetting

You can read more about what the feature achieves in terms of privacy here: https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/

**Comment by Floxbu** [comment]
Thank you Mike! 26.10.2023, 12:29, "Mike Taylor" ***@***.***>: Closed #176 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
