### ISSUE TITLE
Events are rejected in chrome - prohibited by browser policy

### ISSUE THREAD

**Issue by Chaitanya1010** [GoogleChromeLabs/privacy-sandbox-dev-support#177]
When I am running the demo as specified in the docs [here](https://arapi-home.web.app/), I am seeing the following issues:

`Rejected: prohibited by browser policy` status in **Source registrations** in chrome://attribution-internals/
[Rejected: prohibited by browser policy image](https://drive.google.com/file/d/1z5PlvJlu938Xyry3Vl4HrM3rOP6Lda6X/view?usp=drive_link)

`Rejected: prohibited by browser policy` status in **Trigger registrations** in chrome://attribution-internals/
[Rejected: prohibited by browser policy image](https://drive.google.com/file/d/1vjoFhk6Fb-aYUdjnC2GiByhwhQWZ1Va5/view?usp=sharing)

I've made the complete checkout in this [link](https://arapi-advertiser.web.app/checkout) and post that I'm not seeing any reports generated in the Event level reports and Aggregatable reports. This might be expected because the above 2 events aren't considered.
[Checkout page image](https://drive.google.com/file/d/156fp2RO7qjrt89e-35aXeG7YhS0y_GA8/view?usp=sharing)
[No reports in Event-level reports image](https://drive.google.com/file/d/1ppzrpPRbOLorhj3hhuzX9T20Cl3NP-rR/view?usp=sharing)
[No reports in Aggregatable reports image](https://drive.google.com/file/d/1TCubx4ErEVMl1qVN_W-mAUh3L2WNrhuB/view?usp=drive_link)

From the above images we can see that
- Attribution Reporting is enabled.
- Attribution-Reporting-Support is web.
- Report delays are enabled.
- Noise is enabled.

#### Machine config
- chrome - Version 118.0.5993.117 (Official Build) (arm64)
    - Ran it by turning off all the ad blocking extensions
- OS - macOS Sonoma 14.1
    - I've tried this in windows as well with up-to-date chrome, new profile and it's the same
- Chrome settings
    - third party cookies are blocked in ingonito
    - chrome://settings/privacySandbox is redirecting me to chrome://settings/adPrivacy and all the settings there are enabled
    - allowed flags are
        - [privacy-sandbox-ads-apis](chrome://flags/#privacy-sandbox-ads-apis)
        - [privacy-sandbox-settings-4](chrome://flags/#privacy-sandbox-settings-4)
        - [privacy-guide-3](chrome://flags/#privacy-guide-3)

Please let me know what should I do to make sure that the demo runs and I can see the aggregation in chrome://attribution-internals

**Comment by Chaitanya1010** [comment]
Update - facing the same issue when I'm running the code locally with command - `firebase emulators:start --project none`

**Comment by samdutton** [comment]
Thanks for reporting this.

Not 100% sure that this is the cause of the problem you're experiencing, but...

This demo is awaiting [enrollment](https://developer.chrome.com/blog/announce-enrollment-privacy-sandbox/). In the meantime, enable chrome://flags/#privacy-sandbox-enrollment-overrides and add demo origins. Alternatively, run Chrome from the command line, including the flag `--args --disable-features=EnforcePrivacySandboxAttestations`.

**Comment by Chaitanya1010** [comment]
Thank you @samdutton, adding the URLs in chrome://flags/#privacy-sandbox-enrollment-overrides helped me here. I'm able to see the traffic. 
As the issue is resolved, I'm closing this issue.
