### ISSUE TITLE
youtube.com 

### ISSUE THREAD

**Issue by dbunge-mei** [GoogleChromeLabs/privacy-sandbox-dev-support#178]
<html>
<body>
I am getting the message "Cookie set in cross-site context will be blocked in future Chrome versions" with the Domain & Path of ".youtube.com/".  I am using the YouTube video player and I am not setting any specific cookies, so I do not know how to change my site to deal with this issue since it's related to cookies on youtube.com, not any cookies on my site.

Name | Domain & Path
-- | --
VISITOR_INFO1_LIVE | .youtube.com/
YSC | .youtube.com/

</body>
</html>

**Comment by samdutton** [comment]
Hi @dbunge-mei — thanks for you question, and apologies for the delay in responding.

Products and services such as YouTube are aware of the changes referred to in the DevTools issue, and will be making updates to ensure a smooth transition away from third-party cookies as we approach the timeframe for third-party cookie deprecation by Chrome in 2024. [Preparing for the end of third-party cookies](https://developer.chrome.com/en/blog/cookie-countdown-2023oct/) provides timelines and more information.

**Comment by samdutton** [comment]
@dbunge-mei Closing the issue, but feel free to reopen if necessary.
