### ISSUE TITLE
Repo for privacysandbox.com microsite

### ISSUE THREAD

**Issue by dmdabbs** [GoogleChromeLabs/privacy-sandbox-dev-support#180]
[README.md](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/blob/main/README.md) references these information sources...

>You can learn more about the Privacy Sandbox and associated projects at:
>
>    [developer.chrome.com/docs/privacy-sandbox](https://developer.chrome.com/docs/privacy-sandbox)
    [web.dev/digging-into-the-privacy-sandbox](https://web.dev/digging-into-the-privacy-sandbox)
    [chromium.org/Home/chromium-privacy/privacy-sandbox](https://www.chromium.org/Home/chromium-privacy/privacy-sandbox)
    [privacysandbox.com](https://privacysandbox.com/)

Would you kindly please share the GitHub repo for the privacysandbox.com 'microsite?' The others have version controlled repos one can watch/query. Following the microsite repo would permit the community to see when you post updates to the Sandbox timeline or other content of interest. 

Thank you.

**Comment by samdutton** [comment]
Hi David

You could subscribe to the [RSS feed](https://privacysandbox.com/rss/) for privacysandbox.com. 

Does that work?

Sam

**Comment by dmdabbs** [comment]
No. I'm subscribed to that feed.
It only communicates _selected, full_ posts from my experience. 

>Information may change and will be updated monthly.
>Last Update: November 2023 
>The timeline will be updated monthly. 

From [https://privacysandbox.com/open-web/](https://privacysandbox.com/open-web/#:~:text=Information%20may%20change%20and%20will%20be%20updated%20monthly).


There were also changes in October. The ask is to know when privacysandbox.com content changes and what has changed, as is possible for the developer docs, for example, at its repo: https://github.com/GoogleChrome/developer.chrome.com/commits/main/site/en/docs/privacy-sandbox.

**Comment by samdutton** [comment]
Apologies for the delay in posting a response. I did ask the privacysandbox.com team, but they don't have a public repo. 

Privacy Sandbox developer content has [moved from GitHub to a new infrastructure](https://web.dev/blog/webdev-migration), which also doesn't have a public repo. 

We'll do our best to ensure content updates get included in our RSS feeds but, if that isn't adequate, you could use one the web scraping services to observe changes (or run your own using something like [Puppeteer](https://developer.chrome.com/docs/puppeteer)).
