### ISSUE TITLE
Buyer Key Value Server

### ISSUE THREAD

**Issue by TheTamFamily** [GoogleChromeLabs/privacy-sandbox-dev-support#182]
Hi,

First, I would like to clarify which endpoint should be used for retrieving the Key/Values from the Buyer's KV Server.  In https://github.com/WICG/turtledove/blob/main/FLEDGE.md#31-fetching-real-time-data-from-a-trusted-server The HTTP fetch is:

**_https://www.kv-server.example/getvalues?hostname=publisher.com&keys=key1,key2&interestGroupNames=name1,name2&experimentGroupId=12345_**

Where in the https://github.com/WICG/turtledove/blob/main/FLEDGE_Key_Value_Server_API.md explainer the HTTP Fetch is:

**_https://www.dsp-kv-server.example/v1/getvalues?subkey=publisher.com&keys=key1,key2_** 

If the first HTTP Fetch is the one to use then if the browser Fetches using the URL (I have two interest groups with names "tech" and "science" with keys remainingSpend, baseBid and adIndex) :

https://www.kv-server.example/getvalues?hostname=publisher.com&keys=remainingSpend,baseBid,adIndex&interestGroupNames=tech,science 

Should the response look something like:

{
     "tech": {
         "remainingSpend": 12345,
         "baseBid": 3.2,
         "adIndex": [0],
     },
     "science": {
         "remainingSpend": 0,
         "baseBid": 3.2,
         "adIndex": [0,1,2],
     }
  }

Thanks,

David

**Comment by peiwenhu** [comment]
The Key Value Service API is meant to only describe the Trusted Key Value server's API. The Trusted Key Value Server is going to replace the BYOS key value server eventually but right now the main doc for Protected Audience is the one to align with for your BYOS server.

That said, we just made a change to replace the subkey with hostname in the Key Value Service API explainer, so they are consistent now.

**Comment by TheTamFamily** [comment]
Thanks for the clarification.
