### ISSUE TITLE
would this be via a google chrome release?

### ISSUE THREAD

**Issue by gurramv-foxtel** [GoogleChromeLabs/privacy-sandbox-dev-support#193]
hi there,

Can anyone advise, How will google disable 3rd party cookies for 1% of users?
Would users know when they get disabled? Will there be a chrome release for this?

Any response much appreciated.

-Venkat

**Comment by miketaylr** [comment]
Hello, please see https://developers.google.com/privacy-sandbox/3pcd which should explain more.
