### ISSUE TITLE
Tooling for Enterprise

### ISSUE THREAD

**Issue by tejasb09** [GoogleChromeLabs/privacy-sandbox-dev-support#194]
Read https://developer.chrome.com/docs/privacy-sandbox/third-party-cookie-phase-out/ for context before raising issues here.
For site-specific issues with third-party cookies, please report this via https://goo.gle/report-3pc-broken

As per this link: https://developers.google.com/privacy-sandbox/3pcd?utm_source=devtools#test : It is mentioned that Google plans to "provide further reporting and tooling to help identify third-party cookie usage on enterprise sites. "

Please can you advise where I can find this additional tooling ?

**Comment by dmdabbs** [comment]
'Tooling' may be a reference to the Privacy Sandbox Analysis Tool.
https://github.com/GoogleChromeLabs/ps-analysis-tool

**Comment by Airborn22** [comment]
Hi @tejasb09,

@dmdabbs is right, the PS Analysis Tool is one tool like that. The Chrome DevTools' [Issues panel](https://developer.chrome.com/docs/devtools/issues) is also showing errors and warnings related to third-party cookies. These are more developer-centered tools that let you dig deeper on a specific site.
If you are looking for something that is more geared towards enterprise admins, to detect what sites are breaking in your organization, then [CBCM](https://support.google.com/chrome/a/answer/9116814) will support collecting these sites from Chrome 121 by the [Legacy Tech Report](https://support.google.com/chrome/a/answer/7679408?hl=en#:~:text=As%20early%20as%20Chrome%20121%2C%20the%20Legacy,TLS%201.0/1.1%20and%20third%2Dparty%20cookies.)
