### ISSUE TITLE
Inquiry About Changes in Third-Party Cookie Policies

### ISSUE THREAD

**Issue by ConardLi** [GoogleChromeLabs/privacy-sandbox-dev-support#195]
Hello,

We have been recently progressing with the deprecation of third-party Cookies at Bytedance. However, we noticed today that the article you posted on the discontinuation of third-party cookies has been withdrawn. Has there been any change in your plans regarding this?
https://developer.chrome.com/blog/cookie-countdown-2023oct/

Looking forward to your response.
Best regards.

**Comment by johannhof** [comment]
Hi there, thanks so much for reaching out. No change of plans regarding the third-party cookie deprecation. I think there was a migration on the blog recently that may have caused this. @rowan-m can you help get this restored? :)
