### ISSUE TITLE
Enterprise Chrome + Related Websites Sets

### ISSUE THREAD

**Issue by gnilron** [GoogleChromeLabs/privacy-sandbox-dev-support#198]
Is it possible for Enterprise Chrome users to inject company specific RWS into chrome to unlock cross domain cookies.

This could be to allow:

app1.something.com

to embedd

app2.something.com

or even

app3.somethingelse.com

Where both above hostnames are internal company hosts not visible to the internet.

**Comment by cfredric** [comment]
Hi @gnilron, yes, this is possible. Please take a look at the RelatedWebsiteSetsOverrides policy (https://chromeenterprise.google/policies/#RelatedWebsiteSetsOverrides), which lets enterprise admins define enterprise-local sets.

The other RWS policy, RelatedWebsiteSetsEnabled (https://chromeenterprise.google/policies/#RelatedWebsiteSetsEnabled), allows an admin to enable RWS for all their enterprise users.
