### ISSUE TITLE
Not getting expected behavior with 3PCD Deprecation Trial token. 

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#199]
I've registered awsapps.com for the 3PCD Deprecation Trial. I'm setting the trial via an 'Origin-Trial' HTTP header, along with a 'Critical-Origin-Trial' header with value 'Tpcd'. I have a top-level site of https://d33ithtu9f4k36.cloudfront.net/connect/index.html where I'm embedding an awsapps.com domain. I can see the Deprecation Trial token set in DevTools successfully. I have Same-Site = None cookies set for the awsapps.com domain via a different tab. If I open Dev Tools and change the execution context to the awsapps.com domain and do a fetch("/"), I'm seeing the third-party cookies filtered out for the request in the network tab. If I right-click on the filtered cookie and click 'show issues associated with this cookie" it shows it's being blocked because 'reading third-party cookies is blocked'. I only see Partitioned 3P Cookies being sent.

This is happening with and without the test-third-party-cookie phaseout flag enabled.

I see in the url bar that https://d33ithtu9f4k36.cloudfront.net has the Tracking Protection feature automatically blocking third-party cookies. If I click the eye and allow 3P cookies it works. I've found that If I clear my browsing data for the awsapps.com site and https://d33ithtu9f4k36.cloudfront.net, that the Tracking Protection will automatically block 3P cookies once the iframe is loaded. I'm on Chrome version 120.0.6099.71. Does the Deprecation Trial not override Tracking Protection?

<img width="1726" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/d74a76f2-6b7f-43fe-89d4-6c71a3df5da0">

<img width="1726" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/88a73890-fd12-4858-888d-c9b10321e54e">

**Comment by miketaylr** [comment]
@bretticus-mc can you also confirm what version of Chrome you're on? (in chrome://version/)

**Comment by hoodjoshua** [comment]
Also, this is mentioned in the description of `chrome://flags#third-party-cookie-deprecation-trial`, but for the settings created for the Deprecation Trial to actually allow access to third-party cookies, you will need to enable `chrome://flags/#tracking-protection-3pcd` as well.

**Comment by bretticus-mc** [comment]
This is my version
<img width="925" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/44770c49-caad-4b11-a004-663b2d38479f">

**Comment by bretticus-mc** [comment]
I tested the Deprecation Trial successfully using
chrome://flags#third-party-cookie-deprecation-trial -> enabled
chrome://flags/#tracking-protection-3pcd -> enabled

I wasn't aware of these flags. Can y'all add them to the following page?

https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial

**Comment by samdutton** [comment]
One small thing to note: the flag is `chrome://flags/#tpcd-metadata-grants` not `... tcpd ...` as mentioned earlier in this thread.

(@bretticus-mc lists this correctly.)
