### ISSUE TITLE
User-Agent reduction reverse origin trial

### ISSUE THREAD

**Issue by abhi-51deg** [GoogleChromeLabs/privacy-sandbox-dev-support#20]
## Use Discussions for questions
Where to add a domain for User-Agent reduction reverse origin trial? 

It's not visible anywhere in here.
https://www.chromium.org/updates/ua-reduction

Thanks,
Abhi

**Comment by abeyad** [comment]
Hi Abhi, 

If you are asking about the Origin Trial for the [User-Agent Reduction feature](https://chromestatus.com/feature/5704553745874944), we've just created an [Origin Trial](https://developer.chrome.com/origintrials/#/view_trial/-7123568710593282047), but registration for it is currently disabled until support for the trial lands in Chromium.  It is currently slated for the M94 beta release, though it's possible it will slip to M95.  We'll be making an announcement when the Origin Trial is ready for registration and use.

**Comment by abeyad** [comment]
Hi Abhi - just wanted to update you that this Origin Trial will most likely now land in M95.  A blog post and other communication on how to participate will appear around the time the M95 beta release becomes available.

**Comment by samdutton** [comment]
Closing this issue, since the trial completed some time ago.
