### ISSUE TITLE
Total Protection Feature is Blocking Third-Party Cookies By Default

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#200]
It appears Chrome version 120 added a ‘Tracking Protection’ feature that is automatically blocking third-party cookies by default. This seems like unexpected behavior and is affecting our customers’ ability to authenticate with third-party cookies. I see that this feature is rolled back in Chrome Beta version 121. Is there an ETA on when this will be rolled back in Chrome? 

The feature is not enabled by default on version 120.0.6099.62. But is enabled by default on Chrome 120.0.6099.71. You can tell if you have the feature enabled by going to chrome://settings/privacy and seeing a 'Tracking Protection' setting.

Reproduction Steps:

(1) Make sure your Chrome version is Version 120.0.6099.71 or later. 
(2) Go to https://d33ithtu9f4k36.cloudfront.net/connect/index.html
(3) Enter 'https://mcstotts-pdx.my.connect.aws/ccp-v2' in the url bar
(4) Click 'Load CCP'
(5) The url bar will automatically show a closed eyeball. This is the 'Tracking Prevention' feature that is automatically blocking third-party cookies

**Comment by dmdabbs** [comment]
I'm on same Chrome version, but Win64.
I don't see any Tracking Protection enabled in Settings.
I attempted to repro on your test site.  
No eyeball in address bar.
Chrome does block the popup. Console log:

>Refused to display 'https://mcstotts-pdx.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by bretticus-mc** [comment]
Version 120.0.6099.71?

**Comment by bretticus-mc** [comment]
You can see if you have Tracking Protection enabled by going to chrome://settings/privacy and seeing a 'Tracking Protection' setting. 

<img width="1245" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/d008cbdd-f8b8-48fd-940f-3398548660dd">

**Comment by dmdabbs** [comment]
No TP configured....

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/175532/df3f75d5-5967-47d4-80fb-26cd1a934f3c)

**Comment by bretticus-mc** [comment]
Yeah I'm at a loss. One coworker also has this setting on .71. Two others on .71 don't. I'm trying to find if there's a setting we have that's enabled this.

<img width="935" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/be1f8385-99fc-4c87-8426-f16bf09269c7">

**Comment by bretticus-mc** [comment]
One explanation is that my coworker and I have an activated variation for experimenting Total Protection.

https://developer.chrome.com/docs/web-platform/chrome-variations

**Comment by fmacintosh** [comment]
Brett, when you go to chrome://prefs-internals and search for tracking_protection_3pcd_enabled, do you find the value "false" or "true"?

**Comment by bretticus-mc** [comment]
It's set true

**Comment by bretticus-mc** [comment]
But my other coworker experiencing this issue is saying his is set to false...
