### ISSUE TITLE
Disabling the phase-out of 3rd party cookie during the first phase

### ISSUE THREAD

**Issue by sblecon** [GoogleChromeLabs/privacy-sandbox-dev-support#202]
Hello,

During the first step, when 1% of users will be affected by the gradual deletion of third-party cookies, can we rely on the flags from ongoing tests to disable this behavior?

If a user is affected in January by the progressive phase out of third-party cookies, the idea is to use one of the #test-third-party-cookie-phaseout or #tpc-phase-out-facilitated-testing flags to disable it over the Q1 2024 period.

Best regards,
Stéphane

**Comment by krgovind** [comment]
Hi @sblecon, neither of those flags will be effective to disable third-party cookies phaseout. 

Instead, if you are aware of the impacted sites that need access to third-party cookies, those sites should follow the process [here](https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial) to request additional time for migration.

Alternatively, if the impacted users are all on instances of Chrome managed by their employer or educational institution, their administrator can enable third-party cookies for all or specific sites by following the instructions [here](https://support.google.com/chrome/a/answer/7679408?sjid=3930631185439625473-NA#chromeBrsrB120).

Hope that helps!

**Comment by sblecon** [comment]
Thanks a lot @krgovind for your response, it answers to my question.
