### ISSUE TITLE
Definition of "user interaction" in bounce tracking mitigation

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [GoogleChromeLabs/privacy-sandbox-dev-support#204]
Dear Privacy Sandbox team,

I had a quick question regarding the definition of "user interaction" in Chrom(e|ium) in the context of the bounce tracking mitigations.

cf: https://developer.chrome.com/blog/bounce-tracking-mitigations-dev-trial/#what_is_chrome_planning_to_change

I was not able to find a specification or piece of source code describing which actions would be considered "user interactions".
Clicks or keybindings are obvious candidates, but things get fuzzier if we count mouse movement, scrolling or element focus.

Thanks a lot in advance!

**Comment by wanderview** [comment]
Its called a "user activation" in the spec.  See:

https://privacycg.github.io/nav-tracking-mitigations/#bounce-tracking-mitigations-activation-monkey-patch

The html spec definition of user activation:

https://html.spec.whatwg.org/multipage/interaction.html#activation-notification

We also treat successful webauthn assertions as "interactions":

https://privacycg.github.io/nav-tracking-mitigations/#bounce-tracking-mitigations-web-authentication-monkey-patch

**Comment by Mickael-van-der-Beek** [comment]
@wanderview Happy new year 2024! 😃

Thank you very much for both of your answers (on both issues)!

Things are looking clearer on my side. I'll close this issue for now.
