### ISSUE TITLE
Understanding bounce tracking grace period

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [GoogleChromeLabs/privacy-sandbox-dev-support#205]
Dear Privacy Sandbox team,

I juste wanted to clarify without you that my understanding of the 45 day grace period in the bounce tracking mitigation system (DIPS) is correct in situation described down below:

Our example site will be called `tracker.com`. At this stage, no user interaction happened on this site.

1. At t0, `tracker.com` performs a bounce redirection to read and write first party cookies.
2. Between `t0` and `t0 + grace period duration (currently 45 days)`, the browser will allow `tracker.com`  to access state (first party cookies)
3. Once `t0 + grace period + tiny delta` is reached, the browser will activate the DIPS database clearing procedure
4. After `t0 + grace period + timer delay (currently 1 hour) + tiny delta` is reached, state will be wiped for `tracker.com`

Now my question is the following:

If `tracker.com` performs another bounce redirection beyond `t0 + grace period + timer delay + tiny delta`:

Q1: Will the first party cookies set at `t0` be accessible anymore? I would imagine not since they should have been wiped during step (4).
Q2: How long will the newly placed first party cookie last? I would think about 1 hour since the grace period has already been hit once and the timer delay is currently configured at 1 hour.

Would you be able to confirm (or not) my understanding of the DIPS system?

Thank you very much in advance!

**Comment by wanderview** [comment]
I'm sorry, but i think you have misunderstood the time constants.  The suggested grace period is 1 hour, not 45 days.

The 45 days is used instead as a "look back" in history to see if an interaction has occurred on tracker.com.

So it works like this:

- t-44: past event
- t0: tracker.com performs a bounce
- t0.5 (t0 + less than an hour)
- t1 = t0 + 1 hour: deletion algorithm runs

If there was an interaction at t-44 or t0.5 then deletion is prevented when the algorithm runs at t1.

Does that help clarify?

**Comment by Mickael-van-der-Beek** [comment]
@wanderview Happy new year 2024! 😃 

Thank you very much for both of your answers (on both issues)!

Things are looking clearer on my side. I'll close this issue for now.
