### ISSUE TITLE
Question about Third-Party Cookie Disablement in Chrome by Q1 2024

### ISSUE THREAD

**Issue by ConardLi** [GoogleChromeLabs/privacy-sandbox-dev-support#206]
Could you please specify in which Chrome version the 1% disablement of third-party cookies will be implemented, scheduled for release in Q1 2024?

**Comment by miketaylr** [comment]
Release dates for Chrome versions can be found at https://chromiumdash.appspot.com/schedule - thanks.

**Comment by ConardLi** [comment]
@miketaylr Hello, here is the release calendar for different versions of Chrome, but it doesn't specify which version will introduce the 1% disablement of third-party cookies.

**Comment by dmdabbs** [comment]
Last concrete statement I saw was this:

The [Intent to Ship thread](https://groups.google.com/a/chromium.org/g/blink-dev/c/RG0oLYQ0f2I/m/KlmvbrHwBQAJ) for the Deprecate Third Party Cookie feature mentioned M120:

>we're currently planning for early Jan, i.e. M120 would be the first release that contains the technical capabilities to ramp to 1% (breakage mitigations, quantitative testing). 

That doesn't mean the ramp will start then.

**Comment by miketaylr** [comment]
> @miketaylr Hello, here is the release calendar for different versions of Chrome, but it doesn't specify which version will introduce the 1% disablement of third-party cookies.

https://blog.google/products/chrome/privacy-sandbox-tracking-protection/ states that the 1% experiment will begin on January 4th. Hope that helps.

**Comment by ConardLi** [comment]
@miketaylr Hi, it's now the 4th of January, has this update been released yet?

**Comment by krgovind** [comment]
@ConardLi - Yes the rollout to restrict third-party cookies for 1% of Chrome users has begun. Please see [this blogpost](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2024jan) for details.
