### ISSUE TITLE
Testing 3PCD Grace Period

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#207]
The 3PCD Deprecation Trial page [states](https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial#:~:text=We%20acknowledge%20that,the%20grace%20period.) that domains registered for the trial will have a grace period until April 1st, 2024 to implement their token. Is there a Chrome flag where we can test that our application works with this grace period sans token?

**Comment by hoodjoshua** [comment]
If you are manually testing the grace period before January, please enable chrome://flags/#tpcd-metadata-grants in Chrome M121+

**Comment by rowan-m** [comment]
Closing with a note that this is now in the documentation as well: https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial#set_flags_for_testing

Please re-open if there is further discussion needed!

**Comment by bretticus-mc** [comment]
The #tpcd-metadata-grants isn't working for my connect.aws domain. I'm using Chrome Beta Version 121.0.6167.16 (Official Build) beta (arm64).

My flags are:
#tracking-protection-3pcd -> enabled
#tpcd-metadata-grants -> enabled
#third-party-cookie-deprecation-trial -> disabled

I have successfully registered "connect.aws" for the deprecation trial. https://issuetracker.google.com/issues/314796719

1. I go to https://d33ithtu9f4k36.cloudfront.net/connect/index.html
2. I load the third-party site: https://mcstotts-pdx.my.connect.aws
3. Sign in to a second tab, which stores an auth cookie
4. the connect.aws iframe doesn't have access to the cookie. 


<img width="873" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/014e21b3-0863-4106-aa88-b0dfa4cf3790">

**Comment by bretticus-mc** [comment]
Can you reopen the issue? It's not give me the option to

**Comment by samdutton** [comment]
@bretticus-mc reopened!

**Comment by hoodjoshua** [comment]
@bretticus-mc, looking at the associated registration request for the deprecation trial, it looks like you never responded saying that you'd like to sign up for the grace period option.

**Comment by bretticus-mc** [comment]
Oh ok. That was supposed to be communicated in this [ticket](https://issuetracker.google.com/issues/314796719)?

**Comment by bretticus-mc** [comment]
Actually, I found it. I responded to the tickets. Is there still time to be registered for the grace period before the trial begins?

**Comment by rchild-okta** [comment]
I'm also trying to test the grace period behavior - how does the `chrome://flags/#tpcd-metadata-grants` flag work? The description says that it "**Provides a control** for enabling/disabling Third-Party Cookie Deprecation Metadata Grants", but I'm not sure where this control is - is there a setting for this somewhere that I can test locally or is this dependent on finishing the registration for the deprecation trial (and opting into the grace period as noted above)?

**Comment by hoodjoshua** [comment]
@bretticus-mc, Yes, requests to participate in the grace period are still actively being processed.

@rchild-okta the flag itself is the control being referenced in the description.  So, yes, being able to test the grace period behavior with that control enabled is dependent on finishing registration for the deprecation trial and signing up to participate in the grace period. 

When the specified origin(s) has been added to the grace period, the associated registration approval request is updated accordingly. At that point, you should be able to test the grace period behavior locally.

**Comment by bretticus-mc** [comment]
My domains were added and my chrome://components Third-Party Cookie Deprecation Metadata is now 2023.12.26.1. However, I'm still not getting third-party cookie access when I load my domain in an iframe. 

I need the cookie to be present on the first request, so for the deprecation trial token I'm using the Critical-Origin-Trial: Tpcd header. Does the grace period allow 3P Cookies on the first request?
