### ISSUE TITLE
who are the 1% people that will be affected by the Third party cookie breakage

### ISSUE THREAD

**Issue by anjumtadmod1** [GoogleChromeLabs/privacy-sandbox-dev-support#209]
We need to understand if your organization users/project users will be affected by this phasing out. What the 1% users are exactly who will be affected by this.

**Comment by samdutton** [comment]
Hi @anjumtadmod1 — thanks for your question.

> What the 1% users are exactly who will be affected by this.

The 1% deprecation described in [Preparing for the end of third-party cookies](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct) refers to 1% of all Chrome Stable clients, where a "client" is a Chrome installation on a device. Each individual [user data directory](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md) constitutes a distinct client.

The 1% will be randomly selected from all Chrome Stable clients globally, using the [Chrome Variations](https://developer.chrome.com/docs/web-platform/chrome-variations) mechanism.

**Comment by krgovind** [comment]
To add to @samdutton's response; please note that if you're organization's users are on managed instances of Chrome, the administrator can opt users out of the 1% experiment by following instructions [here](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct#enterprise_support).

**Comment by anjumtadmod1** [comment]
Thank you for your response on this @krgovind @samdutton
