### ISSUE TITLE
Wordpress Visual Editor -  Cannot select text

### ISSUE THREAD

**Issue by starpainttech** [GoogleChromeLabs/privacy-sandbox-dev-support#210]
Thank you for taking the time to report a broken web experience related to the blocking of third party cookies. Please follow the instructions below to report your issue.

The Chrome Privacy Sandbox team

Instructions:
Please ensure that this submission is for one specific issue. If you have multiple breakage issues to report, please file them separately to allow for ease of triage by our team.

1. Copy and paste the URL of the broken site.  Wordpress.org, all wordpress sites in the visual editor
2. Describe in detail the problem you experienced, including instructions for our team to reproduce the issue.
 can confirm a bug, but I don’t know where to list it.

A few weeks ago Chrome Beta browser was updated and since then I cannot select any text in visual editor on any of our websites, I cannot double click any text, I cannot even select one word let a lone a sentence.

I cannot even in this visual editor used to report an error on the forum select any text it is very frustrating.

I have deactivated all extensions and reset Chrome beta but it does nto fix it

interestingly, Chrome Dev and Canary also have these problems

In Firefox (which I hate to use) I have no problem and in the Stable normal release of Chrome no problem but we always use beta in our shop because it has faster fixes and better options

I know the last update in Beta talked about alot of new privacy features but I have tried to disable those features,

The problem I think is that eventually the features in Beta will port to Chrome and everyone will have a problem.

3. Please include screenshots of the broken experience.

4. (Optional) Is the affected site used mostly in a managed enterprise setup (i.e. on corporate devices)? NO

5. (Optional) any other pertinent info that may be required. If you are aware of the underlying technical issues, please share as much as you can here.  You will have to contact Wordpress or give us a method to accept 3rd party cookies

**Comment by tunetheweb** [comment]
This is unrelated to the blocking of third-party cookies.

You can find more information about the issue here: https://github.com/WordPress/gutenberg/issues/56408

A fix has been made to WordPress to resolve this and it should be included in a future release (in 6.4.3?).

**Comment by starpainttech** [comment]
Thanks but visual editor works fine in the current stable release of Chrome  so it is not a wordpress version issues
Also the behavior this link you gave is not the issue
I can't double click or select text nothing happens,  the cursor is disabled. I believe the issue they are trying to fix is none relates.

**Comment by tunetheweb** [comment]
If you read the full issue you will see this is a feature that is off by default in Chrome, but about to be enabled. You can turn on `chrome://flags/#enable-experimental-web-platform-features` and it will also break in Chrome stable. In particular see my comment here: https://github.com/WordPress/gutenberg/issues/56408#issuecomment-1830919468

**Comment by starpainttech** [comment]
Ok thanks for the update but this chrome://flags/#enable-experimental-web-platform-features  is disabled in Chrome Beta and I still have the problem anyways I don't work for Wordpress or Google, I am just reporting it so it can be fixed on both ends or wher it needs to be fixed, soon no wordpress developer will be able to edit content , it will be a castrophie

**Comment by tunetheweb** [comment]
In beta it’s enabled by default. As discussed on that other thread.

Closing this now but do let us know if you there is any new information but from all I’ve seen so far it’s covered by that thread and is definitely not to do with the cookie deprecation so comment on that other thread if any more details or concerns.
