### ISSUE TITLE
I am not able see the registration entry  on the trials page where we can see the token.

### ISSUE THREAD

**Issue by avinash-poptani** [GoogleChromeLabs/privacy-sandbox-dev-support#212]
Read https://developer.chrome.com/docs/privacy-sandbox/third-party-cookie-phase-out/ for context before raising issues here.

For site-specific issues with third-party cookies, please report this via https://goo.gle/report-3pc-broken

 I signed up for grace period but I am not able see the registration entry  on the trials page where we can see the token.
 
 
![My_registration_page](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/109739079/554f2861-3d01-4300-82be-5927bd9d76cf)

**Comment by clementsimon** [comment]
Hello @avinash-poptani, please follow each step of the instructions in the [deprecation trial post](https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial#apply_for_the_deprecation_trial). Let us know if you're still experiencing problems.

**Comment by avinash-poptani** [comment]
Thanks @clementsimon .
After resubmitting it worked. For failed registration got below response from support on Ticket
`"Apologies for the trouble here. Our engineering team investigated and it looks like the registration failed on the backend. Can you please register again using the same email address and reference this in your submission?"`

Closing the ticket now.
