### ISSUE TITLE
If I opened "acceptThirdPartyCookies" on android webview, will third-party cookie deprecation affects me?

### ISSUE THREAD

**Issue by Lynn93** [GoogleChromeLabs/privacy-sandbox-dev-support#215]
On android webview, there is an option called "[acceptThirdPartyCookies](https://developer.android.com/reference/android/webkit/CookieManager#acceptThirdPartyCookies(android.webkit.WebView))".

My question is, if I opened this option on android webview, will third-party cookie deprecation affects me?

Looking forward to your reply.
Thanks~!

**Comment by miketaylr** [comment]
Hi there - this API will let you know if 3P cookies are currently enabled or not. For Android Lollipop and below, 3P cookies are in fact enabled by default. Above Lollipop, they are disabled by default, but you can use the https://developer.android.com/reference/android/webkit/CookieManager#setAcceptThirdPartyCookies(android.webkit.WebView,%20boolean) API to re-enable them.

The plans to deprecate 3P cookies in Chrome do not apply to Android WebView. If that changes at some point in the future, we will announce any such plans x to the ecosystem. If your only use case involved WebView, then no - 3PCD will not affect you.
