### ISSUE TITLE
Do Metadata Grants allow 3P Cookies on First Request?

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#217]
My domains (connect.aws and awsapps.com) were added to the 3PCD grace period and my chrome://components Third-Party Cookie Deprecation Metadata is now 2023.12.26.1. However, I'm still not getting third-party cookie access when I load my domains in an iframe. 

I need the cookie to be present on the [first request](https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial#:~:text=If%20you%20need%20cross%2Dsite%20cookies%20to%20be%20on%20the%20very%20first%20request%20to%20your%20origin%20in%20the%20session%2C%20then%20you%20can%20also%20use%20Critical%2DOrigin%2DTrial%20header%20passing%20the%20trial%20name%3A), so for the deprecation trial token I'm using the Critical-Origin-Trial: Tpcd header. Does the grace period allow 3P Cookies on the first request?

I'm testing with 

#tracking-protection-3pcd -> Enabled
#tpcd-metadata-grants -> Enabled
#third-party-cookie-deprecation-trial -> Disabled

<img width="1721" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/e7a24917-e83b-41d8-b6f2-f3f9e8989e35">

<img width="1721" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24796774/f8a935ad-39aa-40a8-bb54-754e25de9ff0">

**Comment by wanderview** [comment]
There should be no problem with first visit.  We believe your domain is not included the given version of the component.  The new version (2024.1.2.3) should be rolling out today.
