### ISSUE TITLE
Google Recaptcha V3 solution after third-party cookie depreaction

### ISSUE THREAD

**Issue by nainesh279** [GoogleChromeLabs/privacy-sandbox-dev-support#223]
Hello,
What needs to be done If we are using Google Recaptcha V3? It is using some cookies which are third-party for our web app (For example: _GRECAPTCHA). What alternative can be done to handle this? What is the solution for this, after deprecation?

**Comment by chhamilton** [comment]
No action is necessary. reCAPTCHA gracefully handles that cookie becoming partitioned (as is already the case with Safari). We will likely be getting rid of that cookie in the future, but there's no rush as things continue to work despite 3PCD.

**Comment by nainesh279** [comment]
Thanks for the update about Google Recaptcha V3. Just wanted to confirm about version V2 also. Any chances that 3PCD will affect Google Recaptcha V2? Do, we need to handle anything specifically for V2 after 3PCD?
