### ISSUE TITLE
No ARA debug reports for users in Mode B

### ISSUE THREAD

**Issue by michal-kalisz** [GoogleChromeLabs/privacy-sandbox-dev-support#224]
Hi,

We've noticed that for users in mode B (treatment_1.*), we aren't receiving debug reports (neither debug nor verbose). However, regular delayed reports are being generated. When registering the source and trigger, we provide a debug key.

Chrome version: 120.0.6099.129 (Official Build) (arm64)
Launched with the flag: --enable-features=CookieDeprecationFacilitatedTesting:label/treatment_1.1/force_eligible/true/disable_3p_cookies/true

According to the description at https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/attribution-reporting-debugging/part-2#set_up_debug_reports_steps_common_to_success_reports_and_verbose_reports, debug reports should be delivered.

Please let me know if you need more details.

**Comment by linnan-github** [comment]
Hi, could you try enabling feature AttributionDebugReportingCookieDeprecationTesting as well to see whether the debug reports are received? Thanks.

--enable-features=CookieDeprecationFacilitatedTesting:label/treatment_1.1/force_eligible/true/disable_3p_cookies/true,AttributionDebugReportingCookieDeprecationTesting

**Comment by michal-kalisz** [comment]
Thank you for the quick response. 
After adding the AttributionDebugReportingCookieDeprecationTesting flag, I am receiving verbose and debug reports.

**Comment by michal-kalisz** [comment]
Thank you for your help. 
Indeed, for real traffic, we receive debug/verbose reports.

**Comment by dmdabbs** [comment]
@linnan-github Is `AttributionDebugReportingCookieDeprecationTesting` only needed when applying `CookieDeprecationFacilitatedTesting`?

**Comment by linnan-github** [comment]
> @linnan-github Is `AttributionDebugReportingCookieDeprecationTesting` only needed when applying `CookieDeprecationFacilitatedTesting`?

Yes, it's only needed when applying CookieDeprecationFacilitatedTesting and disable_3p_cookies being true.
