### ISSUE TITLE
"preperiod" labels

### ISSUE THREAD

**Issue by dmdabbs** [GoogleChromeLabs/privacy-sandbox-dev-support#225]
Now that the experiments have started, how long can the community expect the ["preperiod"](https://developers.google.com/privacy-sandbox/setup/web/chrome-facilitated-testing#pre-period_labels) labels to appear? There are also "prestable*" labels, but at a much lower volume, so not as important. This dominates the labels seen in the wild with "preperiod" outnumbering Mode A experiment group labels. Can we expect these will trail off now that the experiment is in progress?

**Comment by wanderview** [comment]
Sorry for the slow reply.  The `preperiod` labels were disabled at the start of mode-B testing.  As that configuration has ramped up the preperiod labels have been ramping down.  They should represent a very small fraction of traffic at this point.
