### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by ASkyBig** [GoogleChromeLabs/privacy-sandbox-dev-support#226]
## Use Discussions for questions
[https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct?hl=en#preserving_critical_user_experiences](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct?hl=en#preserving_critical_user_experiences)
`for over a quarter of a century.` should translate to `超过四分之一个世纪 `, not `超过25个世纪` in Chinese.

**Comment by miketaylr** [comment]
Thanks for the issue - I've filed an internal bug.
