### ISSUE TITLE
Google Recaptcha V2 solution after third-party cookie depreaction

### ISSUE THREAD

**Issue by nainesh279** [GoogleChromeLabs/privacy-sandbox-dev-support#228]
Hello,
What needs to be done If we are using Google Recaptcha Version 2?
It maybe using some cookies which are third-party for our web app. What alternative can be done to handle this? What is the solution for this, after deprecation?

**Comment by chhamilton** [comment]
No action is required. reCAPTCHA (v2 and v3) will both continue to work as 3PC are deprecated, and the team is actively investing in alternative technologies.

**Comment by miketaylr** [comment]
(linking with previous issue #223)

**Comment by karlhorky** [comment]
Also linking with the issue in `google/recaptcha`:

- https://github.com/google/recaptcha/issues/155
