### ISSUE TITLE
TPCD Trial Token and Critical-Origin-Trial Headers not working as expected

### ISSUE THREAD

**Issue by hectormmg** [GoogleChromeLabs/privacy-sandbox-dev-support#232]
We recently registered two domains (microsoftonline.com and live.com with subdomains enabled) for the third-party cookie deprecation extension trial and we received first-party tokens to test with. However, we haven't been able to get the tokens to work properly.

For context:

- The registered domain is loaded in an embedded hidden iframe and requires 1st request access to third-party cookies.
- For testing, we override the response headers for that first request, including both the `Critical-Origin-Trial: Tpcd` and `Origin-Trial: [1P Token`] headers with the correct values. We do this through a Fiddler script that intercepts and updates the response before it hits the browser.
- We don't see the cookies being added to the request, nor do we see the browser retry the request.
- The Chrome browser Network logs show the correct headers being included in the first 200 response, but the request cookies show up yellow (blocked)
- The same requests still work on my browser if I disable #test-third-party-cookie-phaseout, so we know it's not an issue with the request

I have #tracking-protection-3pcd and #test-third-party-cookie-phaseout enabled in the Experiments/Flags page.

Is there something we're missing here?

For extra context:
1. We initially attempted to inject a third-party enabled token to the top-level frame with JavaScript (without the headers in the iframe). The browser showed the Origin Trial Token was recognized and working in the application tab, but the cross-origin iframe couldn't access the 3p cookies, so we shifted to the approach described above and recommended by the deprecation trial doc:

https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial.

2. We didn't opt into the grace period to have access to 3p cookies without the tokens

Headers in the response:

![1](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/5218163/ad0c548c-2a2d-4774-a626-126f56aa7a77)

Blocked cookies in the request: 
![2](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/5218163/74a19d10-af83-4ddb-bf41-9fab9df48d8c)

Thanks in advance for the help!

**Comment by wanderview** [comment]
What version of chrome are you testing in?  The `#test-third-party-cookie-phaseout` flag has a know issue in M120 that does not permit the deprecation trial to work.  That flag will work in M121, however.

**Comment by hectormmg** [comment]
@wanderview it is in fact 120.0.6099.218. I'll try to update my browser and update this issue, thanks!

**Comment by wanderview** [comment]
You can also try just using `#tracking-protection-3pcd` without the phaseout flag in M120.  Sorry the flags are so confusing at the moment.

**Comment by hectormmg** [comment]
@wanderview thanks a lot for the help, downloaded M121 and it's working as expected!

**Comment by hectormmg** [comment]
Hey folks, re-opening with another question, hope that's okay.

The ["Request additional migration time..." doc](https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial#provide_the_token_in_an_http_header) mentions the following:

>The deprecation trial is provided as a persistent trial, which means that once the token has been received by the browser, the trial behavior will be applied until an iframe is loaded without a trial token present. It is recommended to send the trial token on each iframe load consistently.

However, on Chrome M121, if we load an iframe on the registered domain with the 1p token in the headers once and then stop replying with the headers, access to third-party cookies is maintained. The only way I've been able to "turn off" the origin trial is to restore chrome to default settings and turn all of the flags off (or re-install the beta).

Is this possibly a bug or am I misunderstanding the doc?

**Comment by hoodjoshua** [comment]
When you say you are loading an iframe from the registered domain without providing the 1P token in the response headers to disable the trial, do you mean the exact origin provided in the deprecation trial application? 

If you are using a subdomain matching token, then while the trial can be enabled using any subdomain of the requested origin, in order to disable it an iframe for the requested origin itself (which is stored in the token and can be viewed [here](https://ot-decode.glitch.me/)) has to be loaded without the trial token present.

**Comment by hectormmg** [comment]
@hoodjoshua thanks for clarifying, I missed that mention because of the section title. Closing again.
