### ISSUE TITLE
(Temporary grace period option) Domain allows 3P cookies when the experimental flag is turned on, but not when the user is part of the cohort 

### ISSUE THREAD

**Issue by faraa2m** [GoogleChromeLabs/privacy-sandbox-dev-support#241]
1. We have requested an extension to implement the token on the domains (request: https://issuetracker.google.com/issues/319462981)
2. In chrome 121+ when we turn on the `test-third-party-cookie-phaseout` flag, the 3P cookies are allowed
3. When the  `test-third-party-cookie-phaseout` is off, the user in the video has his 3P cookies disabled (part of the rollout) the 3P cookies are blocked.

https://www.loom.com/share/78905422a04f474892357eedbd505f8f

**Comment by wanderview** [comment]
When chrome://flags/#test-third-party-cookie-phaseout is disabled, what does the chrome cookie settings page look like?  Does it say "tracking protection"?

What other chrome://flags are changed from default values?

**Comment by faraa2m** [comment]
Thank yu @wanderview, the setting was manually turned off.

I will close this issue.
