### ISSUE TITLE
Questions on the Tracking Protection Settings

### ISSUE THREAD

**Issue by rdugenia** [GoogleChromeLabs/privacy-sandbox-dev-support#248]
1. During the testing period (today until Q3 2024) when the `#test-third-party-cookie-phaseout` flag is enabled, the Tracking Protection in the address bar will allow users to re-enable third-party cookies for 90 days on a given site.
  - Is the option to re-enable third-party cookies a one-off thing? What will happen after 90 days?
  - Is the expiration independent of the sites, in cases where multiple sites are allowed?

2. By Q3 2024, when third-party cookies are already deprecated, will the Tracking Protection still be available?

**Comment by kgraney** [comment]
After 90 days the temporary exception created by that UI expires.  You can see the current exceptions and their expiry on chrome://settings/trackingProtection.

The UI in the address bar to create these exceptions is anticipated to remain beyond when third-party cookies are deprecated.  A deprecation timeline for it is TBD, but we don't reasonably expect every website to function without third-party cookies in Q3.

**Comment by rdugenia** [comment]
When the temporary exception expires, will there be an option to enable it again?

**Comment by kgraney** [comment]
Yes, they can be recreated the same way again.  Permanent exceptions are also possible through the settings page.

**Comment by rdugenia** [comment]
Hi, @kgraney. Just a follow-up on my query above, thanks!

**Comment by samdutton** [comment]
Hi @rdugenia 

> I tried adding a site manually to allow the use of third-party cookies, and it doesn't show an expiry date compared to the site that I allow by using the eye icon on the address bar.

I believe that's what @kgraney is referring to. As you say, you don't get an expiry date shown for sites added directly from `chrome://settings/trackingProtection`. That's intentional: the eye icon is to temporarily re-enable third-party cookies for a website, whereas `chrome://settings/trackingProtection` allows a user to set permanent exceptions from third-party cookie restrictions, for an entire domain.

**Comment by rdugenia** [comment]
Hi, @samdutton.

Thank you for the verification! In line with this, if we want to manually add a specific domain under `chrome://settings/trackingProtection`, is there a policy that needs to be configured or how can we apply this across multiple users? So that we don't have to update this setting per user.

**Comment by samdutton** [comment]
> is there a policy that needs to be configured or how can we apply this across multiple users

Two Enterprise policies that might be useful:  

*   [CookiesAllowedForUrls](https://chromeenterprise.google/policies/#CookiesAllowedForUrls) (and `CookiesBlockedForUrls` and `CookiesSessionOnlyForUrls`)  
*  [BlockThirdPartyCookies=false](https://chromeenterprise.google/policies/#BlockThirdPartyCookies)

**Comment by krgovind** [comment]
Please also see [this article](https://support.google.com/chrome/a/answer/14439269) intended for enterprise admins to prepare for third-party cookie phase-out.

**Comment by rdugenia** [comment]
Great! Thank you so much @kgraney, @samdutton, and @krgovind
