### ISSUE TITLE
Origin Trial token doesn't work in Incofnito mode

### ISSUE THREAD

**Issue by vanvodk** [GoogleChromeLabs/privacy-sandbox-dev-support#261]
I came across this issue where TPC is blocked when using Incognito mode, while it works totally fine in regular mode. For the context, the same configuration is setup based on [the guideline](https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial#set_flags_for_testing)

Chrome Version: 123.0.6312.4 
Responses header added:
```
Critical-Origin-Trial: Tpcd
Origin-Trial: <TOKEN_HERE>
```

For the regular mode, I've got 302 Internal Redirect (I believe this is retry with TPC) and follow by a 200 code.

For the incognito mode, I've got 302 Found and ended up in a login challenge page.

Is this expected? I've seen in previous Chrome versions there is an option where we can "Block third-party cookies in Incognito mode" so is it related?

**Comment by tunetheweb** [comment]
This is expected: https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/third-party-deprecation-trial#deprecation_trials

> A deprecation trial reverts the functionality back to how it was before the feature was removed. Third-party cookies may still be blocked by users based on their settings or extensions. They are also blocked by default in Incognito mode. This remains the case for those users and modes even with the deprecation trial.
