### ISSUE TITLE
Bounce Tracking Mitigation and 3PCD Deprecation Trial

### ISSUE THREAD

**Issue by bretticus-mc** [GoogleChromeLabs/privacy-sandbox-dev-support#266]
We have a SAML flow being labeled as bounce tracking. It occurs when the SAML destination (Relay State parameter) is configured to be outside of the domain being federated with. 

The flow is: 
IdP.com -> SAML federation to our domain. We set cookies, then redirect to Relay State -> customer.com, where our app is embedded as an iframe.

I know bounce tracking mitigation is only activated when 3P Cookies are blocked. Just want to confirm this means our customers won't be affected by this mitigation until the Deprecation Trial ends?

**Comment by wanderview** [comment]
Correct.  Chrome's bounce tracking mitigations honors the cookie exceptions created by the deprecation trial.
