### ISSUE TITLE
I have two question. in "Phasing out third-party cookies"! :)

### ISSUE THREAD

**Issue by YoungHyunLee** [GoogleChromeLabs/privacy-sandbox-dev-support#28]
hello,
Dear Google Lab team.

I have two questions.

**1. (Phasing out third-party cookies) So. Third-party cookie phasing out, i'm understand.
but in "Web Storage API", localStorage used third-party data also phasing out?
(cookie and storage same workflow?)**

ex - suppose) origin domain - a.com(first).
ex1) use JS(third), save data for b.com(third) iframe of localstorage
=> like, b.com iframe JS, localstorage.setItem("myBData1", "blob");
or 
ex2) use JS(first), open popup and save data for b.com(third)
=> like, a.com JS, window.open("b.com/saveData?sData=yyyyMMDD_hhmmss"), "bdomainPop");
and b.com/saveData page JS, localstorage.setItem("myBData2", "yyyyMMDD_hhmmss");

then, 
in 2024(third-party cookie phasing out), 
(b.com origin domain page) possible see data "blob" or "yyyyMMDD_hhmmss"? 
like, localstorage.getItem("myBData1") or "myBData2".

**2. (Phasing out third-party cookies) Several documents indicate that "Third-party cookie phasing out", same understand.
Then, is first-patcy cookie right to remain in Web?**

Please, ask my questions...

Thx! for your reading.

**Comment by rowan-m** [comment]
The general approach in the Privacy Sandbox proposals is to create partitions by top-level site (or other equivalent boundary).

We are proposing the `Partitioned` attribute as part of CHIPS to enable use of cookies in cross-site contexts, like an `iframe`, but by creating a separate cookie jar per top-level site. See: https://developer.chrome.com/docs/privacy-sandbox/chips/

We are proposing that this is also the default for other forms of storage, such as `LocalStorage`. See: https://github.com/wanderview/quota-storage-partitioning/blob/main/explainer.md

So, in your example the `LocalStorage` data would be in two separate partitions:

- `https://a.com+https://b.com` → `myBData1`
- `https://b.com` → `myBData2`

First-party or same-site cookies continue to function in the same way as before.

**Comment by YoungHyunLee** [comment]
First.
Thank you so...!! @rowan-m 

Sorry, i read this list.... 
> PSW - Show relevant content and ADS, Measure digital ADS
> PSA - Design Proposal
and remain list "PSW - Strengthen cross-site privacy boundaries" and so on...

Thank you! your comment, and i will read this "Remaining List" article to use my working knowledge.

Have a nice day!


* i'm working "Business planner & IT Designer" and "Front-end Developer"... so every day very busy... (T^ T)

**Comment by samdutton** [comment]
Closing as answered, but feel free to re-open if necessary.
