### ISSUE TITLE
Occurred since Chrome 126: FedCM Accounts API does not show the user in the FedCM dialog if the email is blank.

### ISSUE THREAD

**Issue by solatsuta** [GoogleChromeLabs/privacy-sandbox-dev-support#379]
## Overview
The FedCM Accounts API behaves differently in Chrome 125 and earlier than in Chrome 126 and later when the email address is blank.

In Chrome 126 and later, user selection is no longer possible in the dialog.
I have not been able to find an issue regarding this change, so I am submitting an issue.
If you know of any discussion of the specification change, please let me know.

Thanks for reading this far.
This issue is made in translation. Sorry if the language is strange.

## Details
The Accounts API responds with the following JSON
```
{
  "accounts": [{
    "id": "1234",
    "name": "John Doe",
    "email": "",
    "approved_clients": ["123", "456", "789"],
  }
}
```

For Chrome 125, the FedCM dialog will ask if you want to log in as "John Doe" and the FedCM assertion process will run.
For Chrome 126 and later, the FedCM dialog does not display user information.

We have confirmed that Chrome 126 or later behaves the same as Chrome 125 by including a value such as "dummy@test" in the email field.

## Question
- Is this behavior a specification or a bug?

- If it is a spec, how should IdPs who do not know the user's email address deal with it future Chrome?

**Comment by npm1** [comment]
Do you have a username or something? Perhaps put that while we make the email optional, see https://github.com/fedidcg/FedCM/issues/317

**Comment by samuelgoto** [comment]
> Is this behavior a specification or a bug?

Ugh, this does seem to be a backwards incompatible change that we made that is causing this. Here is the CL that introduced the requirement that email addresses are present, which, as you noted, got into Chrome 126 and above.

https://chromium-review.googlesource.com/c/chromium/src/+/5529788

It is technically neither (a) incompatible with the spec nor (b) a bug, since [email is a required field](https://fedidcg.github.io/FedCM/#dictdef-identityprovideraccount) and this CL is just enforcing that the string is non-empty.

> If it is a spec, how should IdPs who do not know the user's email address deal with it future Chrome?

That's a good question.

Can you help us understand a bit more about your deployment. A few questions:

(a) Do all of your users not have email or just some?
(b) Do you support multiple accounts? Or can the browser assume that you'll have just one entry returned in the accounts endpoint?
(c) If you support multiple accounts, how do your users differentiate between them (a profile picture? a username?)? 
(d) when the RP isn't in the `approved_clients` array, the browser says "do you want to share name, email and profile picture". If the email is unavailable, maybe we should remove the "email" from this list?

**Comment by npm1** [comment]
Followup questions:
1) when the user has a nickname/username, do you share that with the RP or not? What about when the user has an email?
2) how common is it for the user to have an account tied to the cookie and being used for federation? It does not seem optimal to use such an ephemeral account in FedCM so I'm curious.
3) Even though you do not support being logged in to multiple accounts, a user may still have multiple accounts. Do you consider it useful for the UI to show some way to let the user know the precise account being used (eg by showing the nickname) even if that is not shared with the RP?

**Comment by samuelgoto** [comment]
Ok, here is one proposal that came to us:

1) Make `email` optional in the in the [IdentityProviderAccount](https://w3c-fedid.github.io/FedCM/#dictdef-identityprovideraccount) dictionary that we get back from the accounts endpoint and
2) Introduce `username` to the [IdentitityProviderAccount](https://w3c-fedid.github.io/FedCM/#dictdef-identityprovideraccount) dictionary, as an optional string and
3) Introduce `username` to the [Fields API](https://github.com/w3c-fedid/FedCM/issues/559), such that RPs can request for `username` but NOT for `email`, such that the browser doesn't say that the email is going to be shared.

Here is an example of how the RP would call the FedCM API:

```javascript
const credential = await navigator.credentials.get({
  identity: {
    providers: [{
      configURL: ...,
      fields: ["name", "username"] // controls what permission is asked of the user
    }]
  }
});
```

**Comment by samuelgoto** [comment]
Ok, I think we are getting there!

> Add unique_name to the response. it's required value.
> unique_name should be an arbitrary String defined by the IdP.

One of the challenges with taking an arbitrary string is abuse: a spammer can abuse the API to include something like "Get 5% off" and create an intrusion for users.

I was hoping we'd be able to prevent some of this abuse if we could enumerate the types of valid strings (e.g. we can regex email, phone numbers and usernames). An IdP would be able to choose which one to pass to be displayed to the user to disambiguate accounts.

For example:

```javascript
{
 "accounts": [{
   "id": "1234",
   "name": "John Doe",
   "email": "john_doe@idp.example",        // For example, if an IdP has id + email as uniq, has to match emails
   "phone_number": "(630) 023-3243",   // For example, if an IdP has id + phone as uniq, has to be numeric
   "username": "John Doejohn_doe_123456789",  // For example, if an IdP has id + name as uniq, can't contain spaces
   "username": "Jack",                        // For example, if an IdP has id + nickname as uniq, can't contain spaces
   "picture": "https://idp.example/profile/123",
   "approved_clients": ["123", "456", "789"],
   "login_hints": ["john_doe"],
   "domain_hints": ["idp.example"],
  }]
}
```

Would that work?

Or do you have any other type of way to clarify to the user accounts other than `email`, `username`, `phone_number`?

> FieldsAPI can be specified as options. For example, email.

Yeah, I think this would work.

**Comment by samuelgoto** [comment]
> If the interface of the account API call on the RP side remains the same, I think this is a very good approach.

Yeah, that's one of the benefits of this approach: we could make the accounts endpoint response backwards compatible.
