### ISSUE TITLE
Origin trial token inside iFrames

### ISSUE THREAD

**Issue by alois-bissuel** [GoogleChromeLabs/privacy-sandbox-dev-support#38]
Hello,

We have an issue with OT tokens for the attribution reporting API. 
In some cases, our token is declared invalid, its status being "Insecure". I have not been able to find a documentation with all token status and their causes, but I surmise that it comes from our ad being displayed in an insecure iFrame, ie Secure context : No (A frame ancestor is an insecure context).
In our example, all parent iFrames are sourced from https URL. 
The only "trail" that we have is that the top iFrame (a Google ads one) uses a srcdoc attribute, instead of a regular src one.

Let me know if you need some further details.

Thanks a lot for your help!

**Comment by samdutton** [comment]
Hi @alois-bissuel 

That's puzzling.

Would you be able to paste a screenshot of DevTools origin trial information for the page or pages where you're experiencing this? If you can share a link to the page(s), that would be great, but no worries if you can't.

I'll check about `srcdoc`.

```documentation with all token status```

Good idea -- I'll add that to [developer.chrome.com/docs/web-platform/origin-trials ](https://developer.chrome.com/docs/web-platform/origin-trials)or [developer.chrome.com/docs/web-platform/origin-trial-troubleshooting](https://developer.chrome.com/docs/web-platform/origin-trial-troubleshooting).

(@maudnals is out-of-office this week.)

**Comment by alois-bissuel** [comment]
Hi @samdutton ,

Here is a screenshot of the specific token issue. Please tell me if you were expecting something else.
I would love to send you a link to the page, but I don't have a "static" way to reproduce the issue (one has to be retargeted by us for our ads to show up, etc). I could send you the source in a hacky copy-paste manner if this is of any help.

![image](https://user-images.githubusercontent.com/41194547/174060307-ccc1e8b8-1440-4e39-b822-3aa4dd942749.png)

**Comment by samdutton** [comment]
Thanks @alois-bissuel  — I'll take a look.

Just to confirm: `srcdoc` is treated as a same origin iframe: as long as the embedding page is secure, it will be as well.

**Comment by alois-bissuel** [comment]
Hi @samdutton 
Please tell me if you need any further information (html source, etc)

**Comment by DanielRyanSmith** [comment]
Hi there @alois-bissuel. I'm am a member of the Origin Trials support team taking a look at this issue, but I would need some minimal test case to reproduce the problem in order to debug further. Would it be possible to provide this?

**Comment by alois-bissuel** [comment]
Hello @DanielRyanSmith . 
It is the end of the day for me in France, so I don't have the time today to create a real minimal example, but I believe you can reproduce my issue yourself. It might be tedious as it will be probabilistic (you need to get retargeted by Criteo...)
You can visit a large retailer website (such as one starting by Ma and ending by cy's...), and then go to [weather.com](https://weather.com/). 
If you get retargeted by Criteo (all our endpoints have criteo in their name, you can filter it easily), with an ad inside a google ads iFrame (such as as the one highlighted in the image below) with two sandbox.html nested iFrames before our ad, you will land into our issue.
![image](https://user-images.githubusercontent.com/41194547/175344755-5edc1684-90f9-48f7-8b28-ec73223d78bb.png)
Please tell me if this is sufficient, otherwise I will try to hack a custom reproducible minimal working example. It might be hard for me to do it, as I am not sure of what causes the loss of secure context here (all nested iFrames are sourced from https adresses).

**Comment by DanielRyanSmith** [comment]
I tried this method for some time with no luck reproducing 😔 I'm not sure what causes the loss of secure context here either. Any definitive way to reproduce this would be of great help. Sorry about this issue, but thank you for your thorough descriptions and assistance in investigation.

**Comment by fabienbk** [comment]
Hi @DanielRyanSmith (i'm working with @alois-bissuel  on this), Here's an example taken from https://www.lachainemeteo.com/meteo-france/previsions-meteo-france-aujourdhui

The main google ads iframe is deemed "secure"
![image](https://user-images.githubusercontent.com/1923283/175975403-9783a9b3-9935-49e7-bd30-d9f1a4ce51b1.png)

It wraps another intermediary iframe (not owned by us) which chrome defined as insecure context, even though the url is https://s.hubvisor.io/wrapper/01BYK28ENND8X5G8K0AJ2DPK9E/sandbox.html?pid=ban-atf :

![image](https://user-images.githubusercontent.com/1923283/175975561-0a41058f-ceb9-4c99-88f0-e398763f76f1.png)

which seems to disable the attribution-reporting feature altogether. Our code, making use of the attribution api, is running in a child iframe, but to no avail since the feature is disabled by inheritance.

**Comment by maudnals** [comment]
Hi all, it seems we're looking at an overlapping, if not identical issue in #40.
I put together a deployed repro site as well as local repro code and a few observations, see details in https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/40#issuecomment-1168937398.

@DanielRyanSmith and all, feel free to chime in - Thanks!

**Comment by DanielRyanSmith** [comment]
Thanks a lot for the demo @maudnals! I am seeing what is being described in your comment using your demo. I'm still unsure of the cause unfortunately, but I'll update here if I have any additional info.

**Comment by maudnals** [comment]
Hi @alois-bissuel @fabienbk 
I'm trying to reproduce this specific issue, so we can loop in the right folks and get additional Chrome Eng support on this.
I can't see this in the **Frames** panel, any idea / any other place where I can try and reproduce?

<img width="433" alt="Screenshot 2022-07-15 at 13 23 07" src="https://user-images.githubusercontent.com/9762897/179213934-64997bd9-9b75-40e4-bdb8-9ef53a5e0a0b.png">

**Comment by alois-bissuel** [comment]
Hello @maudnals,

I have looked at the issue again, and I haven't been able to find any definitive proof that a redirect happens or not for the creation of these iFrames. The only hint is that the "topmost" hubvisor iFrame in devtool (Application tab) has a button close to the URL to get the associated network request, and this request has an http code 304. This is a form of redirect to a cached resource if I am not mistaken. I do not know whether this might cause an issue or not, and I have no idea how to reproduce this in a controlled manner.

**Comment by alois-bissuel** [comment]
Closing, as this might be covered in #52.
