### ISSUE TITLE
how to share cookies accross domains owned by same owner

### ISSUE THREAD

**Issue by ngoyal16** [GoogleChromeLabs/privacy-sandbox-dev-support#39]
How to share cookies accross domains owned by same owner. and cookies which needs to be shared is third party cookie which domain again belongs to same owner.

**Comment by ddadon10** [comment]
@ngoyal16 : You can check the First party set initiative[1]

[1]:https://developer.chrome.com/docs/privacy-sandbox/first-party-sets/

**Comment by samdutton** [comment]
@rowan-m FYI

**Comment by rowan-m** [comment]
Closing off as this does look like the documentation resolves the issue, but please do re-open if there are more questions.
