### ISSUE TITLE
Remove the permissions policy need in cross-origin iFrames during the OT

### ISSUE THREAD

**Issue by alois-bissuel** [GoogleChromeLabs/privacy-sandbox-dev-support#41]
Hello,

I have a question regarding the need to allow the attribution reporting API in cross-origin iFrames during the . The adtech ecosystem relies a lot on cross-origin iFrames, and not all actors may be aware that this origin trial is going on and that other partners may test it. We see that some actors allow the API, but some don't do it. Thus we see that we cannot test the API on all the ads we serve.

Would it be possible to remove the requirement of permissions policy during the course of the OT? 

On the long run, the ecosystem will adapt and I expect all actors to allow the API (as they will either need it themselves, or might be compelled by contractual obligations), but I think it is unreasonable to ask for every actor to adapt quickly only for the OT.

**Comment by maudnals** [comment]
Hi @alois-bissuel (apologies for the delay, I was ooo)

IMU disabling the permissions policy isn't desirable even during the OT, given it's a security/trust feature.
I'm in touch with the Chrome Eng team too and will come back to you with details.

IMU your biggest issue at the moment is nested iframes, is this correct? E.g. what you're encountering in https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/38?

For discussion on the blocks caused by Permissions Policy, I've filed https://github.com/WICG/attribution-reporting-api/issues/519 (as this is a spec question that only happens to overlap with the OT).

**Comment by alois-bissuel** [comment]
Thanks Maud for the answer.

My issue is more broad than the nested iframes problem described in #38. Some actors in the adtech industry are not aware that this OT is taking place, and don't bother passing on the permission. I am sure that if the attribution reporting API were to be put in production, these actors would (in the long run after some adaptation) allow this API, hence my desire to remove the permission policy system. This would enable a better understanding of the performance by the final users of this API.
In the long run, a permission policy system is more than desirable, as it is a trust feature.
To me, it all depends on what the aim of the OT is. Do we want to showcase the complexity of the adtech ecosystem, or simply test the pure performance of the API?

**Comment by maudnals** [comment]
Thank you Alois, we're aligned. I completely understand this is an issue for experimentation.
I'm in touch with Chrome Eng and we're discussing options to mitigate this problem.
I'll come back to this thread when I hear back.

**Comment by maudnals** [comment]
No concrete updates just yet, but just a heads-up that a proposal to mitigate this issue is currently being evaluated.

**Comment by maudnals** [comment]
Hi @alois-bissuel, one related question: 
Are you using feature detection with the API? 
If so, in which ways is feature detection helping or not helping you correct your cookie-based vs ARA-based measurement results?

**Comment by alois-bissuel** [comment]
Hello @maudnals 

Sorry for the very late answer, I was in vacations!

We are using feature detection for a correct usage of the API (when using `window.open`), but not for correcting the measurement we get from the API. We do this by offline correlation of unique ids which we use for both our standard ads system and the attribution-reporting API.

**Comment by maudnals** [comment]
Noted, thank you. 
We'll come back to this thread as soon as we have details to share.

**Comment by maudnals** [comment]
Update: the Permissions-Policy default allowlist has been changed during the testing phase, to mitigate both this issue (#41) and issue #52. No code changes are needed from your side. Find all the details on the change and its timeline [in this post](https://groups.google.com/u/0/a/chromium.org/g/attribution-reporting-api-dev/c/uFmCrdaUjqw).

Thank you for reporting this problem and working with us towards a solution!

Let us know in case you have a question/need troubleshooting on this change, by filing an issue here in this repo as usual.

**Comment by alois-bissuel** [comment]
Thanks a lot for the support!
Closing the issue as the change will solve our problem.
