### ISSUE TITLE
How to configure AttributionSrc to receive ads interactions?

### ISSUE THREAD

**Issue by MiQ-Sakthi** [GoogleChromeLabs/privacy-sandbox-dev-support#42]
Hello Team,

Would require some help/readme.txt to configure attributionsrc to receive and learn ads interactions, attribute conversions - event level and summary level reports.

- What should be the Attributionsrc server specification to receive feedbacks from the browser?

- How often attribution report would be PUSHED by "Google Canary/Chrome 101 browser" to adserver and What are the steps to be followed to configure push frequency in the browser?

- What should be the Attributionsrc endpoint/contract signature - documentation/payload sample could help here.

Regards,

R.Sakthi

**Comment by maudnals** [comment]
Hi @MiQ-Sakthi, 

Thanks for reaching out!
The [handbook](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.kyhr8dm2gw6q) should contain the answers to your questions:


> What should be the Attributionsrc server specification to receive feedbacks from the browser?

See:
[Set up an endpoint to collect aggregatable reports](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.hfuxnt7z0oum)
[Set up an endpoint to collect event-level reports](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#bookmark=id.otf0h66sfptq)


> How often attribution report would be PUSHED by "Google Canary/Chrome 101 browser" to adserver

⚠️ Please use Chrome Canary to get the latest version of the API; Chrome 101 isn't recommended.
See:
[Report scheduling for aggregatable reports](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.72gv73ha3ykw)
[Report scheduling for event-level reports](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.c5k14yezmbvl)

> What are the steps to be followed to configure push frequency in the browser?

* While you can't configure the frequency at which the browser sends reports, you can configure for event-level reports the [expiry](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#bookmark=id.s2kjnd4jtffl), which will impact the [report scheduling](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#bookmark=id.j82aaw68q6qw)
* For local debugging purposes, you can [get the reports immediately](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.msoxkz63ojug)
* For prod debugging purposes, you can set up [debug reports](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#bookmark=kix.xm0mmx7cmrtp).


> What should be the Attributionsrc endpoint/contract signature - documentation/payload sample could help here.

Please refer to the [demo and code](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.vk0ctjqbpr1g).

Hope this helps!
In case you have any questions which aren't answered in the documentation, please feel free to ask.
