### ISSUE TITLE
FLEDGE Trial Token

### ISSUE THREAD

**Issue by TheTamFamily** [GoogleChromeLabs/privacy-sandbox-dev-support#45]
HI,

I have registered for FLEDGE FOT and received a trial token as a 3rd party provider.  

I use the following javascript to add the trial token to my website:

(function() {
	const token = 'A+wsKTCrz8EsvZ2NydwYsQKbcoWn51pPkzU3TFWNeRKXCuCLzJR8Za+0sBc+p5l4Ox6aBTavuVj2L6OwJJNiwgAAAACEeyJvcmlnaW4iOiJodHRwczovL3Rkbi5yNDJ0YWcuY29tOjQ0MyIsImZlYXR1cmUiOiJQcml2YWN5U2FuZGJveEFkc0FQSXMiLCJleHBpcnkiOjE2NjEyOTkxOTksImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9';

	function addTrialToken(token) {
		const tokenElement = document.createElement('meta');
		tokenElement.httpEquiv = 'origin-trial';
		tokenElement.content = token;
		document.head.appendChild(tokenElement);
	}

	addTrialToken(token);
})();
       
The browser does not see this token even though I can see this on the webpage.

Thanks,

David

**Comment by maudnals** [comment]
Hi @TheTamFamily,

> The browser does not see this token even though I can see this on the webpage.

What does the [DevTools token panel](https://developer.chrome.com/docs/web-platform/origin-trial-troubleshooting/#use-chrome-devtools-to-check-tokens) display? What's the status of the token?

Have you had a chance to go through these [origin trial troubleshooting tips](https://developer.chrome.com/docs/web-platform/origin-trial-troubleshooting)?

**Comment by samdutton** [comment]
Also — did you provide the third-party origin trial token via an external script (not an inline script)?

**Comment by samdutton** [comment]
Hi David — did this work out in the end?

**Comment by TheTamFamily** [comment]
Hi Sam,

This worked. Apologies for the delay as I am currently on holiday.

Thank you,
David

**Comment by samdutton** [comment]
Thanks David! Good to hear. I'll close this now, but reopen if you need to.
