### ISSUE TITLE
UACH and GoogleBot

### ISSUE THREAD

**Issue by prash-mi** [GoogleChromeLabs/privacy-sandbox-dev-support#5]
Posting on behalf of Blibli:

How to detect GoogleBot using UA going forward. Currently Blibli check the "compatible" section of the UA string:

`Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (**compatible; Googlebot/2.1; +http://www.google.com/bot.html**)`

I think this section will be missing after UA is deprecated and UACH will give us the following information:

```
Sec-CH-UA: "Chromium";v="84", "Google Chrome";v="84"
Sec-CH-UA-Mobile: ?0
```

I understand that the recommended way to detect Google bot is to do a reverse DNS lookup as described [here](https://developers.google.com/search/docs/advanced/crawling/verifying-googlebot). The question is that when UA retires then would such usecases where the clients are detecting the bot using UA break?

**Comment by rowan-m** [comment]
No immediate news here, but changes to crawler user-agent strings would be announced over on https://developers.google.com/search as usual.

**Comment by 2297435** [comment]
I do not have a website and do not know why my information seems to everywhere. Thanks

**Comment by rowan-m** [comment]
Closing off as this should be covered by Google Search documentation—but on the whole, the expectation is that Googlebot should not deviate from Chrome in too much of a surprising way.
