### ISSUE TITLE
Remove the need for OT tokens except in the iFrame calling the API

### ISSUE THREAD

**Issue by alois-bissuel** [GoogleChromeLabs/privacy-sandbox-dev-support#52]
Following a [comment](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/44#issuecomment-1218328241) from @johnvidel in #44, it looks like OT tokens are needed in every parent frame of any iFrame using the API (as well as the correct permission-policy), including the top-level context. For an ad to be registered as a "source", the current OT technical setup requires both
a) providing a valid token 
b) including the attribute "allow=attribution-reporting" declaration 
in the top-level context (only for the token) and each iframe the ad is embedded in.

Most DSPs, including Criteo, display ads that are not directly integrated in the top-level context, but through one or several iframes originating from the page publisher and SSPs. This requires the publisher (or SSPs having direct top-level integration), and the one or several SSPs building cascading iFrames embedding the ad to do (a) and (b).

Looking at the data we are collecting as of today, it seems that no publisher/SSP is doing so, i.e. we are getting less than 1% of the source events we expect. This limits a lot the analysis and insight we could get out of the OT.

How can we solve this issue? 

- Onboarding multiple SSPs in the trial seems difficult before the end of the OT.
- Would it be possible to relax the token / trust delegation system?
- Any other solution?

Note: this is very similar to our previous ask of removing the permission policy system during the OT (#41)

**Comment by maudnals** [comment]
Hi Alois,
Agree that this closely relates to #41.
Relaxing the policy by setting its default allowlist to `*` for the OT should help mitigate both issues #41 and #52 (as in this case, the parent iframe does not need to inject the OT token).
We'll post updates on these issues as the proposal is being evaluated.

**Comment by alois-bissuel** [comment]
Thanks a lot. Closing it, as issue #41 describes most closely what we want.

**Comment by maudnals** [comment]
Update: the Permissions-Policy default allowlist has been changed during the testing phase, to mitigate both this issue (#41) and issue #52. No code changes are needed from your side. Find all the details on the change and its timeline [in this post](https://groups.google.com/u/0/a/chromium.org/g/attribution-reporting-api-dev/c/uFmCrdaUjqw).

Thank you for reporting this problem and working with us towards a solution!

Let us know in case you have a question/need troubleshooting on this change, by filing an issue here in this repo as usual.
