### ISSUE TITLE
FloC print in index.php

### ISSUE THREAD

**Issue by Rutto17** [GoogleChromeLabs/privacy-sandbox-dev-support#6]
## Use Discussions for questions

*Issues should only be used for documentation hosted in this repo. If that's the
case, delete all this text and raise the issue.*

I'm trying to send the cohort value to my index.php. Someone can help me?

async function asyncCall() {
var cohort = await document.interestCohort();
let url = new URL("https://http.cat/408");
url.searchParams.append("cohort", cohort);
creative = await fetch(url);
console.log(creative);

**Comment by samdutton** [comment]
Hi @Rutto17

To use FLoC, you will need to run Chrome with flags, or take part in the origin trial. 

If you're not doing either of these, see [Take part in the FLoC origin trial](https://developer.chrome.com/blog/floc/#take-part-in-a-floc-origin-trial) and [Enable FLoC with browser flags](https://developer.chrome.com/blog/floc/#enable-floc-with-browser-flags).

**Comment by samdutton** [comment]
Closing this, but feel free to reopen if necessary.
