### ISSUE TITLE
Question about event-level rate attribution limit

### ISSUE THREAD

**Issue by cjzcpsyx** [GoogleChromeLabs/privacy-sandbox-dev-support#65]
Recently, we sometimes get this error message when doing testing with chrome webdriver:
**Attributable: reached event-level attribution limit**
I see the [doc](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#reporting-cooldown--rate-limits) on rate limit says:
**Strawman rate limit: 100 attributions per {source site, destination, reporting origin, 30 days}**
However, our test case is creating a new webdriver session each time, and is run in a hermetic environment, and the cases are way lower than 100 pairs for each target.

So just wonder:
1. Is there a way to bypass the limit when starting chrome (with launch param)
2. Is there a way to reset the limit count during test run time?
3. How is the limit is collected, does it persist across webdriver sessions

Thanks ahead.

**Comment by csharrison** [comment]
Do you know what [User Data Dir](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md) selenium is using in your environment? It seems likely that the tests are re-using the same state across runs (i.e. are not actually hermetic)

**Comment by hongzhu3142** [comment]
Hi Charlie, 

I followed your instruction to clear the use data for every test case. The flakes reduced a lot. However, I got some failed tests: the first registration has the status of attributable:event-level rate attribution limit, and the registrations after that are fine (status is "attributable").

Is there any other factor that can lead to this flakes?

Thanks.

**Comment by rowan-m** [comment]
Closing this issue after a period of inactivity, but please re-open if it's still relevant!
