### ISSUE TITLE
Commandline flags to enable Privacy Sandbox API with requiring OT token for local testing 

### ISSUE THREAD

**Issue by zhengweiwithoutthei** [GoogleChromeLabs/privacy-sandbox-dev-support#69]
According to this [doc](https://developer.chrome.com/en/blog/privacy-sandbox-unified-origin-trial/#local-testing), the APIs in the browser can be enabled for testing in one of the following two ways:

- Enable chrome://flags/#privacy-sandbox-ads-apis

- Run Chrome from the command line with the following flags:

`--enable-features=BrowsingTopics,PrivacySandboxAdsAPIsOverride,OverridePrivacySandboxSettingsLocalTesting`

However, both approaches enable the API features without requiring Origin Trial token. Bypassing the Origin Trial token check disguises any problem related to the token itself. Such as, missing token, expired token, wrong 1p vs. 3p token, invalid token, etc.

It is very important to make sure our testing infrastructure is capable of testing the real user setup (i.g. browser client is selected in the trial branch, requiring OT token to activate the trial and enable the APIs). 

Please consider providing a commandline flags that enforces the trial and requiring the OT token to enable the APIs.

**Comment by jkarlin** [comment]
@zhengweiwithoutthei If you remove the PrivacySandboxAdsAPIsOverride then I believe the OT should be required to expose the API.

**Comment by zhengweiwithoutthei** [comment]
Thanks you both for following up the feedback. It looks like removing PrivacySandboxAdsAPIsOverride does't trick! I want to suggest Chrome to document the variance of this flag. It will be really helpful.

**Comment by zhengweiwithoutthei** [comment]
It looks like FencedFrame doesn't work with this approach. For example, with commandline flags:
--enable-features=InterestGroupStorage,AdInterestGroupAPI,Fledge,FencedFrames
and a valid OT token, nagivator.runAdAuction() is enabled but window.HTMLFencedFrameElement is still undefined.

**Comment by shivanigithub** [comment]
> It looks like FencedFrame doesn't work with this approach. For example, with commandline flags: --enable-features=InterestGroupStorage,AdInterestGroupAPI,Fledge,FencedFrames and a valid OT token, nagivator.runAdAuction() is enabled but window.HTMLFencedFrameElement is still undefined.

That's expected since fenced frames require both PrivacySandboxAdsAPIsOverride and FencedFrames flags to be enabled.
IIUC the ask here is to have a new flag which will enable a feature only if the required feature flags and the OT token are both valid.

**Comment by zhengweiwithoutthei** [comment]
That is correct. For other Sandbox APIs, it looks like --enable-features= [feature] without PrivacySandboxAdsAPIsOverride satisfy the requirement, except for FencedFrame. I would expect that `--enable-features=FencedFrames` + valid OT token should be sufficient to enable Fenced Frame.

**Comment by jkarlin** [comment]
Do you also have PrivacySandboxAdsAPIs required? I think you need `--enable-features=FencedFrames,OverridePrivacySandboxSettingsLocalTesting,PrivacySandboxAdsAPIs`

**Comment by zhengweiwithoutthei** [comment]
Thanks @jkarlin 
No, I don't have it. What is that flag for? Is it only required for FencedFrames? It looks like other APIs don't need it.

**Comment by jkarlin** [comment]
Huh, I believe it should be required for any of the APIs to work. Perhaps you've enabled one of the flags as well via chrome://flags that enables it?

**Comment by zhengweiwithoutthei** [comment]
I do not have the chrome://flags. I did some more tests and here is the result. For the most part, it works as expected. FLEDGE is the one that confused me. 

### Things works as expected:

  **All PS APIs in OT**
  `--enable-features=BrowsingTopics,InterestGroupStorage,AllowURNsInIframes,PrivacySandboxAdsAPIs`
  Requires OT token for Topics, FF, FLEDGE, Reporting
  
  **Topics**
  `--enable-features=BrowsingTopics`
  Not enabled even with OT token
  
  `--enable-features=BrowsingTopics,PrivacySandboxAdsAPIsOverride`
  Enables document.browsingTopics() by default without requiring OT token
  
  `--enable-features=BrowsingTopics,PrivacySandboxAdsAPIs`
  Enables  document.browsingTopics() with valid OT token only
  
  **Fenced Frame**
  
  --enable-features=FencedFrames
  Not enabled even with OT token
  
  --enable-features=FencedFrames,PrivacySandboxAdsAPIsOverride
  Enables HTMLFencedFrameElement by default without requiring OT token
  
  --enable-features=FencedFrames,PrivacySandboxAdsAPIs
  Enables  HTMLFencedFrameElement with valid OT token only

### Things doesn't work as expected (or my expectation is wrong):

  **FLEDGE**
  --enable-features=AdInterestGroupAPI,InterestGroupStorage,Fledge
  Enables navigator.runAdAuction() by default without requiring OT token
  
  **Attribution reporting**
  The API enable status on Chrome://attribution-internals is misleading. It shows ‘enabled’ if the chrome://flags is true or the Chrome instance is in the Finch experiment. In the latter case, an OT token is still required to enable the feature. Without the token, document.featurePolicy.allowsFeature('attribution-reporting') = false
![image](https://user-images.githubusercontent.com/99193721/208516995-01e3fa6a-d690-45fd-8af7-dab2c4d6f3a0.png)

  
  Both feature detection method mentioned in this [doc](https://developer.chrome.com/en/blog/privacy-sandbox-unified-origin-trial/#attribution-reporting) are either wrong or not ideal:
  1. Checking`'attributionReporting' in window `no longer works.
  2. Checking `document.featurePolicy.allowsFeature('attribution-reporting')` will trigger "unrecognized feature: 'attribution-reporting'" warning, if the feature is not enabled. Instead, we should check `document.featurePolicy.allowedFeatures().include('attribution-reporting')`

**Comment by jkarlin** [comment]
For FLEDGE, try just `--enable-features=InterestGroupStorage,PrivacySandboxAdsAPIs`

In regards to attribution, I think being "enabled" is correct in the internals page in the sense that the browser is processing attributions/conversions when they're used on pages (via OTs). It's mostly an internal architecture thing (the javascript surface being exposed is controlled by the OT, the feature being enabled within the browser for processing is a different feature controlled by the field trial. 

Perhaps @samdutton can speak to the docs.

**Comment by zhengweiwithoutthei** [comment]
thanks @jkarlin. Glad to know things WAI. I also updated the result to include SharedStorage API.

**Comment by jkarlin** [comment]
@jensenpaul should know more about what's going on with the fledge flags than I do. But it should certainly be possible to set up a situation in which the OT token is required and the API is otherwise enabled via the command line.

**Comment by JensenPaul** [comment]
Requiring OT tokens seems to imply opting someone into the OT, which I don't know how to do.  [As we mentioned](https://groups.google.com/a/chromium.org/g/fledge-api-announce/c/5bta-AqrOCY/m/oPnuDsPxBAAJ) however, the pre-stable channels (i.e. Beta, Canary, Dev) are 50/50 split for OT eligibility so, an easy (though not deterministic) way to get into the OT (and hence require the OT token) is probably to install one of the pre-stable channel browsers, and if you're not in the 50% you want to be in, then reinstall.

**Comment by zhengweiwithoutthei** [comment]
Thanks @JensenPaul . The approach you suggested works for local testing but not with an automated test frameworks (e.g. with WebDriver). Also, testing only with pre-stable channels are not sufficient.  Ideally, the flag `Fledge` should work the same way as other Sandbox API flags. I would imagine something like:

--enable-features=Fledge
Not enabled even with OT token

--enable-features=Fledge,PrivacySandboxAdsAPIsOverride
Enables Fledge related APIs by default without requiring OT token

--enable-features=Fledge,PrivacySandboxAdsAPIs
Enables Fledge related APIs  with valid OT token only

**Comment by jkarlin** [comment]
Try `--enable-features=InterestGroupStorage,PrivacySandboxAdsAPIs,BiddingAndScoringDebugReportingAPI,AllowURNsInIframes` which has the extra features that I believe you need.
