### ISSUE TITLE
Integration issue for ARA

### ISSUE THREAD

**Issue by alois-bissuel** [GoogleChromeLabs/privacy-sandbox-dev-support#74]
We wanted to share with you some issues we have with the testing at scale of the Attribution Reporting API.
 
Looking broadly at the number of sources and triggers, we get only 3% of sources and triggers on our endpoint compared to our production log, when we should have a figure closer to the true share of the OT (ie 5%). When breaking down the analysis per advertiser, all possible cases happen regarding the integration on source and trigger side (eg we have advertisers with good integration for sources and bad for triggers, good for both, bad for both, etc).
 
When further looking into reports, we have unexpected results. We have a set-up where we track all types of events on the advertiser’s website but give sales a higher priority, to be sure that we get all clicks which effectively led to an event on the advertiser’s website while still being able to track all sales. A preliminary analysis showed that we get overall a low number of reports (with a share close to 1%, once again to be compared to 5%).

We have just implemented verbose debug reports. We did not have time enough yet to do some full investigations on them yet, but so far we have not seen any obvious red flags there (such as `source-unknown-error` or `trigger-unknown-error` which would indicate a malformed call to the reporting API).

Would you have any other lead for our investigation?
Thanks a lot!

**Comment by jkarlin** [comment]
Thank you for experimenting with the API, and thanks for asking these questions.  I think there is some common misunderstanding here, which perhaps we should publish somewhere. 

The 5% of users in the OT are not 5% of all of Chrome's stable users, it's 5% of all of Chrome's stable users that have metrics collection enabled. I don't know what fraction of users that is, but that would explain some of the drop. Also, not all users have the sandbox experimental APIs enabled (e.g., for the OT experiment, the APIs are opt-in in Europe). So, I'm not surprised to see the discrepancy that you report. 

But it seems reasonable to want to know how users that do have the API enabled compare in source/trigger volume to your log data. @johnivdel might be able to help with that.

**Comment by johnivdel** [comment]
Thanks for filing!

I have a few clarification questions:

> Looking broadly at the number of sources and triggers, we get only 3% of sources and triggers on our endpoint compared to our production log, when we should have a figure closer to the true share of the OT (ie 5%). 

Could you clarify what API invocations you are using to register sources and triggers? E.g. fetch, attributionsrc, attributionsrc=, etc. That will help me understand what various things could be going wrong.

In terms of the number of sources and triggers: we generally recommend that testers try to get a clean slice of data to look at which includes traffic in the OT. In the past, we have recommended that you annotate sources/triggers in the production logic with a boolean containing the value of `document.featurePolicy.allowsFeature("attribution-reporting")`. Only logs where this is true should be considered for analysis and ensures that the browser/event occurred within the 5% enabled population.

It is recommended to do this in conjunction with the debug keys so you can match a report/debug report directly to the source/trigger log, see https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting-debugging/part-2/#set-up-debug-reports-steps-common-to-success-reports-and-verbose-reports

Depending on what API you are using/whether you have JS running, it ma be difficult to do this, so please let me know if this isn't viable.

> A preliminary analysis showed that we get overall a low number of reports (with a share close to 1%, once again to be compared to 5%).

Could you clarify if this 1% is for all reports, or just sales reports?

I would recommend to try and first do a comparison of expected reports with debug reports (the ones sent immediately at conversion time), as this will control for some sources of loss like user initiated data deletion / delays / etc. See https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting-debugging/part-2/#set-up-success-debug-reports

From there, comparing the debug reports to the final reports will give a better breakdown of where loss is occurring.

If you are already doing any of these things, let me know and I can make further suggestions, thanks!

**Comment by alois-bissuel** [comment]
Hello,
Thanks for you answers. I was in holidays before, hence my late reply.

Regarding API invocations, we are using on the source side both the HTML (ie `attributionsrc` attribute) and the JS one (ie the supplementary parameter `attributionsrc` in `window.open`). On the trigger-side, we are using a pixel integration (ie `attributionsrc` attribute in the pixel tag).

> In terms of the number of sources and triggers: we generally recommend that testers try to get a clean slice of data to look at which includes traffic in the OT.

I am not sure to fully understand what you are trying to say. Could you elaborate further on the meaning of "clean slice of data"?

We have not annotated our production logs with a flag which indicates the availability of the API. What we currently do is log all the calls to our source and trigger registration endpoints. I believe your annotation idea would enable to track integration issues between our answers to the registration calls and the actual registration. It would fail to detect issues stemming from tokens though.

I forgot to specify that we are using debug reports for our analyses (this makes it easier to get meaningful figures). We are indeed already looking at a comparison between standard and debug reports to get a grasp of the delays and data deletion coming from the user.

> Could you clarify if this 1% is for all reports, or just sales reports?

I forgot to mention that this figure is valid for all reports. We have analysed in more depth the sales reports, but we don't see a big difference for other type of events.

@jkarlin 
>The 5% of users in the OT are not 5% of all of Chrome's stable users

We would not have been surprised had we gotten more than 4% for sources and triggers, but 3% seems abnormally low. Would you have any figure of the "true" participation rate in places where the OT is not opt-in?

**Comment by isaac0731** [comment]
![image](https://user-images.githubusercontent.com/70382548/212847267-fde76efd-48ed-4205-bc0d-62441e3f6649.png)

**Comment by zhijzurong** [comment]
https://source.android.com/devices/tech/admin/multi-user?hl=zh-tw#managing_users

**Comment by maudnals** [comment]
@alois-bissuel 
Hi Alois, we're not sure what may cause the issue (maybe a user setting opt-out, but this is just speculation).
Are you still observing this? Anything the verbose debug reports investigation has revealed?

**Comment by maudnals** [comment]
Sounds good, thank you.

**Comment by alois-bissuel** [comment]
Coming back after a long pause.
We tried looking at the verbose debug reports and we have some unexpected results.
It looks like we have approximately half of the sources (clicks) for which we get a verbose debug report (most of the time a `source-success` and sometimes indicating that we hit some privacy limit). On the trigger side, the ratio leans more towards two thirds. These ratio appears too far from what manual tests indicate (ie we have failed to see real-life integration problems).
To be totally transparent, I have not checked that it is not due to the `ar_debug` cookie not being properly set (we set it only if we don't find it in the ARA ping, this might create an issue if we falsely think this is set, but I don't see why this could be the case). We might look further down this path if needed.

**Comment by dmdabbs** [comment]
>approximately half of the sources (clicks) for which we get a verbose debug report (most of the time a source-success and sometimes indicating that we hit some privacy limit

Thanks for the report @alois-bissuel. Chrome team, I can't recall specific Monorail items at the moment, but I've read issues where some API behavior may be impacted when the document context (to which some pending background event/beacon is associated) disappears/freezes/&c. such as during navigation. If such a thing was addressed might this be older milestones?

**Comment by dmdabbs** [comment]
I just re-read and realised that I thought you had said that you'd received half the verbose reports. Doh.
