### ISSUE TITLE
Hov

### ISSUE THREAD

**Issue by hovh154** [GoogleChromeLabs/privacy-sandbox-dev-support#82]
### To request a feature, fill the field below

**Feature you'd like to see**
_Describe the feature and the problem it would solve_

### To report a bug, fill the fields below

**Version**
_Paste the version number of Noise Lab you're using (displayed on the top left of Noise Lab)_

**Bug**
_Describe the bug_

**How to reproduce**
_Add steps to reproduce the behavior_
3. See error
4. ...

**Expected behavior**
_Describe what you expected to happen._

**Screenshots**
_If possible, add screenshots to help explain your problem._

**Comment by hovh154** [comment]
realme C35

**Comment by miketaylr** [comment]
This is spam, and @hovh154 is probably a bot.
