### ISSUE TITLE
How to test PAA + Fledge?

### ISSUE THREAD

**Issue by michal-kalisz** [GoogleChromeLabs/privacy-sandbox-dev-support#94]
Hi,
[Two weeks ago really nice feature was introduce](https://chromium-review.googlesource.com/c/chromium/src/+/4083309): report event from FF previously registered in reportWin/generateBid function (by 
privateAggregation.reportContributionForEvent)

I run canary Chrome with enable features PrivateAggregationApi,PrivateAggregationApiFledgeExtensions (--enable-features=PrivacySandboxAdsAPIsOverride,InterestGroupStorage,Fledge,BiddingAndScoringDebugReportingAPI,AllowURNsInIframes,BrowsingTopics,ConversionMeasurement,FencedFrames,OverridePrivacySandboxSettingsLocalTesting,SharedStorageAPI,PrivacySandboxAdsAPIs,PrivateAggregationApi,PrivateAggregationApiFledgeExtensions)

In generate bid I added:
```
  privateAggregation.reportContributionForEvent('imp', {bucket: 3n, value: 5});
  privateAggregation.reportContributionForEvent('reserved.win', {bucket: 5n, value: 6});
```
In ad:
`window.fence.reportEvent("imp");`

My bid won an auction and an ad was rendered:
- I haven't received report on win,
- When ad calls reportEvent("imp"). The exception was raised:
_Uncaught SecurityError: Failed to execute 'reportEvent' on 'Fence': FLEDGE extensions must be enabled to use reportEvent() for private aggregation events."_

It seems that my chrome configuration is incorrect. 
In mentioned change there is comment:
> The `Fence` class needs access to the feature flag
> `kPrivateAggregationApiFledgeExtensions`. That flag has been moved as
> part of this CL from "content/common/private_aggregation_features.*" to
> a runtime-enabled feature in "runtime_enabled_features.json5".
How To Enable this feature?

Best Regards, 
Michal

**Comment by alexmturner** [comment]
Hey @michal-kalisz , thanks for tagging me. We've changed the feature definitions slightly -- instead of the separate PrivateAggregationApiFledgeExtensions feature, the fledge extensions is now a parameter on the PrivateAggregationApi feature. To enable it, I believe the following should work on the latest Canary: `--enable-features= PrivacySandboxAdsAPIsOverride,...,PrivateAggregationApi:fledge_extensions_enabled/true`. (But please let me know if it doesn't!)

Separately, we are also planning to enable these extensions in the Canary/Dev Origin Trial very soon.

**Comment by michal-kalisz** [comment]
Hi @alexmturner, Thanks a lot! 
With these flags PAA works for both: reserved.* and trigger by ad. No matter if I use an iframe or a fenced frame. 
That's great!
But as far as I tested it does not work with ad components, I received (when using Fenced frame):
_This frame did not register reporting metadata._

I think there are no privacy concerns with aggregated reporting  (as it is for event level reporting - i.e. FFAR)
Would you consider support triggering PAA from ad components?
Or maybe it will be supported along with https://github.com/WICG/turtledove/issues/332 ?

BR,
Michal

**Comment by alexmturner** [comment]
Hi @michal-kalisz , thanks for the feedback! Yes, I believe that fixing the issue you linked should also add support for PAA. Once the implementation is complete, I'll be happy to make sure it did.

**Comment by michal-kalisz** [comment]
Hi @alexmturner, 
Indeed, once https://chromium-review.googlesource.com/c/chromium/src/+/4381472 was merged, triggering reporting PAA on ad components works as expected.
Thanks for support,
Michal

**Comment by alexmturner** [comment]
Great to hear! Thanks for the update
