### ISSUE TITLE
Same origin restrictions with Fenced Frame reporting API

### ISSUE THREAD

**Issue by fhoering** [GoogleChromeLabs/privacy-sandbox-dev-support#98]
We made some tests using the FF reporting API in Fledge/ARA with different domains on Chrome 111 and Chrome 112:

```
registerAdBeacon({
          'display': 'https://test.domain.com',
          'click': 'https://test.domain.com',
          "reserved.top_navigation": 'https://test.domain.com'
 });
```

On chrome 111 (Stable)
- It seems like there is a restriction that all registered urls must be of same origin as the initial Fledge tagging/bidding domain. Otherwise no event is sent at all

On chrome 112 (Beta)
- All events are fired independently of their domain. Even not being SameSite works.

Can you confirm that the new behavior is the intended one ?

From a general point of view the new behavior seems reasonable because otherwise it means that the Fledge tagging domain and ARA trigger domain must be of same origin which heavily links both APIs.

**Comment by shivanigithub** [comment]
Thanks for raising this! 
The behavior you are seeing in M112 is indeed the intended one.

**Comment by fhoering** [comment]
OK. thanks.
